/**
 * Meat & Fish recipe completion data — 70 recipes (MainMeat + MainFish)
 */
import type { RecipeCompletionMap } from "../complete-recipes";

export const MEAT_FISH_DATA: RecipeCompletionMap = {
  // ══════════════════════════════════════════════════
  // PANIERTES (10)
  // ══════════════════════════════════════════════════
  "Wiener Schnitzel (Kalb)": {
    ingredients: [
      { name: "Kalbsschnitzel", amount: 600, unit: "g", allergens: [] },
      { name: "Mehl glatt", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 150, unit: "g", allergens: ["A"] },
      { name: "Butterschmalz", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Fleisch zwischen Frischhaltefolie dünn klopfen (3-4 mm)",
      "Salzen und pfeffern",
      "In Mehl wenden, durch verquirlte Eier ziehen, in Semmelbröseln panieren",
      "In reichlich heißem Butterschmalz schwimmend herausbacken (170°C)",
      "Dabei die Pfanne schwenken, damit die Panade souffliert",
      "Auf Küchenpapier abtropfen lassen, mit Zitronenspalte servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Wiener Schnitzel (Schwein)": {
    ingredients: [
      { name: "Schweineschnitzel", amount: 600, unit: "g", allergens: [] },
      { name: "Mehl glatt", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 150, unit: "g", allergens: ["A"] },
      { name: "Butterschmalz", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Fleisch zwischen Frischhaltefolie dünn klopfen",
      "Salzen und pfeffern",
      "Panierstraße: Mehl, Ei, Semmelbrösel",
      "In heißem Butterschmalz schwimmend herausbacken (170°C)",
      "Pfanne schwenken für soufflierte Panade",
      "Auf Küchenpapier abtropfen, mit Zitrone servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Backhendl": {
    ingredients: [
      { name: "Hühnerstücke (Keule, Brust)", amount: 800, unit: "g", allergens: [] },
      { name: "Mehl glatt", amount: 100, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 150, unit: "g", allergens: ["A"] },
      { name: "Butterschmalz", amount: 300, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
      { name: "Paprikapulver", amount: 1, unit: "TL", allergens: [] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Hühnerstücke waschen, trocknen, salzen und mit Paprika würzen",
      "30 Minuten marinieren lassen",
      "In Mehl wenden, durch Ei ziehen, in Semmelbröseln panieren",
      "In heißem Fett goldbraun herausbacken (170°C, ca. 12-15 Min)",
      "Auf Küchenpapier abtropfen lassen",
      "Mit Zitronenspalten und Petersilkartoffeln servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Cordon Bleu": {
    ingredients: [
      { name: "Schweineschnitzel groß", amount: 4, unit: "Stk", allergens: [] },
      { name: "Kochschinken", amount: 4, unit: "Scheiben", allergens: [] },
      { name: "Emmentaler", amount: 4, unit: "Scheiben", allergens: ["G"] },
      { name: "Mehl", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 150, unit: "g", allergens: ["A"] },
      { name: "Butterschmalz", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Schnitzel aufschneiden und aufklappen (Schmetterlingsschnitt)",
      "Schinken und Käse einlegen, zuklappen und Ränder gut andrücken",
      "Salzen und pfeffern",
      "Panieren: Mehl, Ei, Semmelbrösel",
      "In heißem Fett goldbraun herausbacken (170°C, ca. 8 Min pro Seite)",
      "Auf Küchenpapier abtropfen, mit Zitrone servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Putenschnitzel paniert": {
    ingredients: [
      { name: "Putenschnitzel", amount: 600, unit: "g", allergens: [] },
      { name: "Mehl", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 120, unit: "g", allergens: ["A"] },
      { name: "Sonnenblumenöl", amount: 200, unit: "ml", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Putenschnitzel dünn klopfen, salzen und pfeffern",
      "Panierstraße: Mehl, verquirlte Eier, Semmelbrösel",
      "In heißem Öl goldbraun herausbacken",
      "Auf Küchenpapier abtropfen, mit Zitrone servieren",
    ],
    allergens: ["A", "C"],
  },
  "Gebackene Leber": {
    ingredients: [
      { name: "Kalbsleber", amount: 500, unit: "g", allergens: [] },
      { name: "Mehl", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 120, unit: "g", allergens: ["A"] },
      { name: "Butterschmalz", amount: 150, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
      { name: "Majoran", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Leber in Scheiben schneiden, Häutchen entfernen",
      "Salzen und mit Majoran würzen",
      "Panieren: Mehl, Ei, Semmelbrösel",
      "In heißem Butterschmalz goldbraun herausbacken",
      "Auf Küchenpapier abtropfen, mit Erdäpfelpüree servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Gebackener Karpfen": {
    ingredients: [
      { name: "Karpfenfilet", amount: 600, unit: "g", allergens: ["D"] },
      { name: "Mehl", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 120, unit: "g", allergens: ["A"] },
      { name: "Butterschmalz", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Karpfenfilets in Portionsstücke schneiden",
      "Salzen, pfeffern und mit Zitronensaft beträufeln",
      "10 Minuten ziehen lassen, dann panieren",
      "In heißem Butterschmalz goldbraun herausbacken (170°C)",
      "Auf Küchenpapier abtropfen, mit Erdäpfelsalat servieren",
    ],
    allergens: ["A", "C", "D", "G"],
  },
  "Pariser Schnitzel": {
    ingredients: [
      { name: "Kalbsschnitzel", amount: 600, unit: "g", allergens: [] },
      { name: "Mehl", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Butter", amount: 80, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Schnitzel dünn klopfen, salzen und pfeffern",
      "In Mehl wenden, durch verquirltes Ei ziehen (KEINE Brösel!)",
      "Sofort in heißer Butter goldbraun braten",
      "Auf Küchenpapier abtropfen",
      "Mit Zitronenspalte und Erbsenreis servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Surschnitzel": {
    ingredients: [
      { name: "Surschnitzel (gepökeltes Schwein)", amount: 600, unit: "g", allergens: [] },
      { name: "Mehl", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 120, unit: "g", allergens: ["A"] },
      { name: "Butterschmalz", amount: 150, unit: "g", allergens: ["G"] },
      { name: "Kren frisch", amount: 30, unit: "g", allergens: [] },
    ],
    steps: [
      "Surschnitzel leicht klopfen",
      "Panieren: Mehl, Ei, Semmelbrösel",
      "In heißem Fett goldbraun herausbacken",
      "Mit frisch geriebenem Kren und Erdäpfelsalat servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Hühnerschnitzel Natur paniert": {
    ingredients: [
      { name: "Hühnerbrustfilet", amount: 600, unit: "g", allergens: [] },
      { name: "Mehl", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 120, unit: "g", allergens: ["A"] },
      { name: "Sonnenblumenöl", amount: 150, unit: "ml", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Hühnerbrust in Schnitzel schneiden und flach klopfen",
      "Salzen und pfeffern",
      "Panieren: Mehl, Ei, Semmelbrösel",
      "In heißem Öl goldbraun braten (je Seite ca. 4 Min)",
      "Auf Küchenpapier abtropfen",
    ],
    allergens: ["A", "C"],
  },

  // ══════════════════════════════════════════════════
  // BRATEN & SCHMORGERICHTE (20)
  // ══════════════════════════════════════════════════
  "Schweinsbraten": {
    ingredients: [
      { name: "Schweinsschulter / Bauch", amount: 1200, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 3, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 3, unit: "Stk", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "EL", allergens: [] },
      { name: "Rindssuppe", amount: 500, unit: "ml", allergens: ["L"] },
      { name: "Bier dunkel", amount: 200, unit: "ml", allergens: ["A"] },
      { name: "Salz", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Schwarte rautenförmig einschneiden, Fleisch salzen und mit Kümmel und Knoblauch einreiben",
      "Bei 200°C im Ofen anbraten, Schwarte nach oben",
      "Zwiebeln grob schneiden und dazugeben",
      "Regelmäßig mit Bier und Suppe begießen",
      "2-2.5 Stunden braten bis die Schwarte knusprig ist",
      "Saft entfetten und als Sauce servieren",
    ],
    allergens: ["A", "L"],
  },
  "Kümmelbraten": {
    ingredients: [
      { name: "Schweinshals", amount: 1000, unit: "g", allergens: [] },
      { name: "Kümmel ganz", amount: 2, unit: "EL", allergens: [] },
      { name: "Knoblauch", amount: 4, unit: "Stk", allergens: [] },
      { name: "Zwiebeln", amount: 2, unit: "Stk", allergens: [] },
      { name: "Rindssuppe", amount: 400, unit: "ml", allergens: ["L"] },
      { name: "Salz", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Fleisch ringsum salzen und großzügig mit Kümmel und Knoblauch einreiben",
      "Bei 180°C im Ofen auf Zwiebelbett setzen",
      "Regelmäßig mit Suppe begießen",
      "2 Stunden braten, Sauce abseihen und entfetten",
    ],
    allergens: ["L"],
  },
  "Stelze": {
    ingredients: [
      { name: "Schweinsstelze", amount: 2, unit: "Stk", allergens: [] },
      { name: "Kümmel", amount: 2, unit: "EL", allergens: [] },
      { name: "Knoblauch", amount: 4, unit: "Stk", allergens: [] },
      { name: "Bier dunkel", amount: 500, unit: "ml", allergens: ["A"] },
      { name: "Salz", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Stelzen in Salzwasser mit Kümmel 90 Minuten vorkochen",
      "Schwarte rautenförmig einschneiden, mit Knoblauch einreiben",
      "Bei 200°C im Ofen knusprig braten (ca. 45 Min)",
      "Regelmäßig mit Bier begießen",
      "Mit Sauerkraut und Senf servieren",
    ],
    allergens: ["A"],
  },
  "Tafelspitz": {
    ingredients: [
      { name: "Tafelspitz (Rindfleisch)", amount: 800, unit: "g", allergens: [] },
      { name: "Karotten", amount: 200, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 100, unit: "g", allergens: ["L"] },
      { name: "Lauch", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Pfefferkörner", amount: 5, unit: "Stk", allergens: [] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Fleisch in kaltem Wasser aufsetzen und langsam zum Sieden bringen",
      "Schaum abschöpfen, Gewürze zugeben",
      "Bei niederer Hitze 2.5-3 Stunden sieden lassen (nicht kochen!)",
      "Suppengemüse in der letzten Stunde zugeben",
      "Fleisch gegen die Faser aufschneiden",
      "Mit Schnittlauchsauce, Semmelkren und Apfelkren servieren",
    ],
    allergens: ["L"],
  },
  "Zwiebelrostbraten": {
    ingredients: [
      { name: "Beiried / Rostbraten", amount: 4, unit: "Stk", allergens: [] },
      { name: "Zwiebeln", amount: 4, unit: "Stk", allergens: [] },
      { name: "Mehl", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Rindssuppe", amount: 200, unit: "ml", allergens: ["L"] },
      { name: "Senf", amount: 1, unit: "EL", allergens: ["M"] },
      { name: "Butterschmalz", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Fleisch mit Senf bestreichen, salzen und pfeffern",
      "Zwiebeln in Ringe schneiden, in Mehl wenden",
      "Zwiebelringe in Butterschmalz goldbraun frittieren, beiseite stellen",
      "Fleisch scharf anbraten (je Seite 3-4 Min für medium)",
      "Bratensatz mit Rindssuppe ablöschen, einkochen",
      "Fleisch mit Röstzwiebeln und Sauce servieren",
    ],
    allergens: ["A", "G", "L", "M"],
  },
  "Rindsbraten": {
    ingredients: [
      { name: "Rindsschulter", amount: 1000, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 3, unit: "Stk", allergens: [] },
      { name: "Karotten", amount: 200, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 80, unit: "g", allergens: ["L"] },
      { name: "Tomatenmark", amount: 2, unit: "EL", allergens: [] },
      { name: "Rotwein", amount: 200, unit: "ml", allergens: ["O"] },
      { name: "Rindssuppe", amount: 400, unit: "ml", allergens: ["L"] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Fleisch salzen, pfeffern und in heißem Öl rundherum scharf anbraten",
      "Herausnehmen, Zwiebeln und Gemüse im Bratfett rösten",
      "Tomatenmark einrühren, mit Rotwein ablöschen",
      "Fleisch zurücklegen, Suppe und Lorbeer zugeben",
      "Bei 160°C im Ofen 2.5 Stunden schmoren",
      "Sauce abseihen und pürieren, Fleisch aufschneiden",
    ],
    allergens: ["L", "O"],
  },
  "Sauerbraten": {
    ingredients: [
      { name: "Rindfleisch (Schulter)", amount: 1000, unit: "g", allergens: [] },
      { name: "Rotweinessig", amount: 200, unit: "ml", allergens: [] },
      { name: "Rotwein", amount: 200, unit: "ml", allergens: ["O"] },
      { name: "Zwiebeln", amount: 2, unit: "Stk", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Gewürznelken", amount: 3, unit: "Stk", allergens: [] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Lebkuchen", amount: 30, unit: "g", allergens: ["A", "H"] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Fleisch 3-4 Tage in Essig-Wein-Marinade mit Gewürzen einlegen",
      "Herausnehmen, trockentupfen und scharf anbraten",
      "Gemüse aus der Marinade mitrösten",
      "Mit gefilterter Marinade ablöschen",
      "2.5 Stunden bei 160°C schmoren",
      "Sauce mit zerbröseltem Lebkuchen binden",
    ],
    allergens: ["A", "H", "O"],
  },
  "Kalbsbraten": {
    ingredients: [
      { name: "Kalbsschulter", amount: 1000, unit: "g", allergens: [] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Karotten", amount: 150, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 60, unit: "g", allergens: ["L"] },
      { name: "Weißwein", amount: 200, unit: "ml", allergens: ["O"] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Kalbfleisch salzen und in Butter rundherum anbraten",
      "Gemüse zugeben und mitrösten",
      "Mit Weißwein ablöschen, Thymian zugeben",
      "Bei 160°C 90 Minuten im Ofen schmoren",
      "Sauce abseihen, Schlagobers einrühren",
      "Fleisch aufschneiden und mit Sauce servieren",
    ],
    allergens: ["G", "L", "O"],
  },
  "Faschierter Braten": {
    ingredients: [
      { name: "Faschiertes gemischt", amount: 700, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 2, unit: "Stk", allergens: [] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 60, unit: "g", allergens: ["A"] },
      { name: "Senf", amount: 1, unit: "EL", allergens: ["M"] },
      { name: "Paprikapulver", amount: 1, unit: "TL", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Zwiebel fein hacken und in Butter anschwitzen, abkühlen",
      "Faschiertes mit Ei, Semmelbröseln, Senf, Petersilie und Gewürzen verkneten",
      "Zu einem Laib formen und in eine gefettete Form geben",
      "Bei 180°C 50-60 Minuten backen",
      "10 Minuten rasten lassen, in Scheiben schneiden",
    ],
    allergens: ["A", "C", "M"],
  },
  "Tellerfleisch": {
    ingredients: [
      { name: "Rindfleisch (Brustkern)", amount: 800, unit: "g", allergens: [] },
      { name: "Karotten", amount: 150, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 80, unit: "g", allergens: ["L"] },
      { name: "Lauch", amount: 80, unit: "g", allergens: [] },
      { name: "Pfefferkörner", amount: 5, unit: "Stk", allergens: [] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Fleisch in kaltem Wasser aufsetzen und zum Sieden bringen",
      "Schaum abschöpfen, Gewürze zugeben",
      "2-3 Stunden bei niedriger Hitze sieden lassen",
      "Gemüse in den letzten 30 Minuten zugeben",
      "Fleisch in Scheiben aufschneiden, mit Suppe und Gemüse servieren",
      "Dazu Semmelkren und Schnittlauchsauce reichen",
    ],
    allergens: ["L"],
  },
  "Geselchtes mit Sauerkraut": {
    ingredients: [
      { name: "Selchfleisch (Geselchtes)", amount: 600, unit: "g", allergens: [] },
      { name: "Sauerkraut", amount: 500, unit: "g", allergens: ["O"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Schmalz", amount: 30, unit: "g", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Lorbeerblatt", amount: 1, unit: "Stk", allergens: [] },
      { name: "Wacholderbeeren", amount: 3, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Geselchtes in Wasser 60 Minuten weich kochen",
      "Zwiebel in Schmalz anschwitzen, Sauerkraut zugeben",
      "Kümmel, Lorbeer und Wacholder zugeben, 30 Minuten dünsten",
      "Geselchtes in Scheiben schneiden",
      "Mit Sauerkraut und Knödeln servieren",
    ],
    allergens: ["O"],
  },
  "Selchfleisch": {
    ingredients: [
      { name: "Selchfleisch (Schopf)", amount: 800, unit: "g", allergens: [] },
      { name: "Wasser", amount: 2000, unit: "ml", allergens: [] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Pfefferkörner", amount: 5, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Selchfleisch in kaltem Wasser aufsetzen",
      "Mit Lorbeer und Pfeffer langsam zum Sieden bringen",
      "90 Minuten bei niedriger Hitze ziehen lassen (nicht kochen)",
      "Aufschneiden und mit Kren und Senf servieren",
    ],
    allergens: [],
  },
  "Spanferkel": {
    ingredients: [
      { name: "Spanferkelstücke", amount: 1200, unit: "g", allergens: [] },
      { name: "Knoblauch", amount: 4, unit: "Stk", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "EL", allergens: [] },
      { name: "Bier", amount: 200, unit: "ml", allergens: ["A"] },
      { name: "Salz", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Schwarte einschneiden, Fleisch mit Salz, Kümmel und Knoblauch einreiben",
      "Bei 200°C anbraten (30 Min), dann auf 160°C reduzieren",
      "Regelmäßig mit Bier begießen",
      "2-2.5 Stunden braten bis Schwarte knusprig kracht",
      "Saft entfetten und als Jus servieren",
    ],
    allergens: ["A"],
  },
  "Lammkeule": {
    ingredients: [
      { name: "Lammkeule", amount: 1500, unit: "g", allergens: [] },
      { name: "Knoblauch", amount: 6, unit: "Stk", allergens: [] },
      { name: "Rosmarin", amount: 3, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 3, unit: "EL", allergens: [] },
      { name: "Weißwein", amount: 200, unit: "ml", allergens: ["O"] },
      { name: "Kartoffeln", amount: 500, unit: "g", allergens: [] },
      { name: "Salz", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Knoblauch in Stifte schneiden und ins Fleisch spicken",
      "Mit Olivenöl und Rosmarin einreiben, salzen",
      "Bei 200°C anbraten, dann auf 160°C reduzieren",
      "Kartoffeln und Wein zugeben, 2 Stunden schmoren",
      "Fleisch rasten lassen, Sauce entfetten",
    ],
    allergens: ["O"],
  },
  "Lammkarree": {
    ingredients: [
      { name: "Lammkarree", amount: 800, unit: "g", allergens: [] },
      { name: "Knoblauch", amount: 3, unit: "Stk", allergens: [] },
      { name: "Rosmarin", amount: 2, unit: "Stk", allergens: [] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 3, unit: "EL", allergens: [] },
      { name: "Semmelbrösel", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Senf", amount: 1, unit: "EL", allergens: ["M"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Lammkarree parieren und salzen",
      "In heißem Olivenöl rundherum scharf anbraten",
      "Mit Senf bestreichen, Kräuter-Semmelbrösel-Mischung andrücken",
      "Bei 180°C 15-20 Minuten im Ofen rosa garen (Kerntemp. 58°C)",
      "10 Minuten rasten lassen, dann in Koteletts schneiden",
    ],
    allergens: ["A", "M"],
  },
  "Schweinemedaillons": {
    ingredients: [
      { name: "Schweinefilet", amount: 600, unit: "g", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Champignons", amount: 150, unit: "g", allergens: [] },
      { name: "Weißwein", amount: 100, unit: "ml", allergens: ["O"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Filet in 3 cm dicke Medaillons schneiden",
      "Salzen, pfeffern und in Butter beidseitig 3 Min braten",
      "Herausnehmen und warmhalten",
      "Champignons im Bratfett anbraten, mit Wein ablöschen",
      "Schlagobers zugeben, einkochen lassen",
      "Medaillons in der Sauce servieren",
    ],
    allergens: ["G", "O"],
  },
  "Putenbraten": {
    ingredients: [
      { name: "Putenbrust", amount: 1000, unit: "g", allergens: [] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 50, unit: "g", allergens: ["L"] },
      { name: "Weißwein", amount: 150, unit: "ml", allergens: ["O"] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Putenbrust salzen, pfeffern und in Butter anbraten",
      "Gemüse dazugeben und mitrösten",
      "Mit Weißwein ablöschen, Thymian zugeben",
      "Bei 160°C 60-75 Minuten im Ofen garen",
      "Sauce abseihen, Schlagobers einrühren",
      "Fleisch aufschneiden und mit Sauce servieren",
    ],
    allergens: ["G", "L", "O"],
  },
  "Entenkeule": {
    ingredients: [
      { name: "Entenkeulen", amount: 4, unit: "Stk", allergens: [] },
      { name: "Zwiebel", amount: 2, unit: "Stk", allergens: [] },
      { name: "Äpfel", amount: 2, unit: "Stk", allergens: [] },
      { name: "Orangensaft", amount: 200, unit: "ml", allergens: [] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Entenkeulen salzen und mit Thymian würzen",
      "In eine Bratform legen, bei 180°C anbraten",
      "Zwiebel und Äpfel vierteln und dazugeben",
      "Mit Orangensaft begießen, 90 Minuten braten",
      "Regelmäßig begießen, bis die Haut knusprig ist",
      "Saft entfetten und als Sauce servieren",
    ],
    allergens: [],
  },
  "Ganslbraten": {
    ingredients: [
      { name: "Gans (küchenfertig)", amount: 3000, unit: "g", allergens: [] },
      { name: "Äpfel", amount: 3, unit: "Stk", allergens: [] },
      { name: "Maroni", amount: 200, unit: "g", allergens: [] },
      { name: "Beifuß", amount: 2, unit: "Stk", allergens: [] },
      { name: "Zwiebeln", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Gans innen und außen salzen, mit Beifuß und Äpfeln füllen",
      "Brust nach unten auf ein Gitter über Fettpfanne legen",
      "Bei 180°C 3-3.5 Stunden braten",
      "Nach der Hälfte wenden, Brust nach oben",
      "Regelmäßig mit Bratfett begießen",
      "Gansl tranchieren, mit Rotkraut und Knödeln servieren",
    ],
    allergens: [],
  },
  "Rehragout": {
    ingredients: [
      { name: "Rehfleisch (Schulter)", amount: 800, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 2, unit: "Stk", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 50, unit: "g", allergens: ["L"] },
      { name: "Rotwein", amount: 300, unit: "ml", allergens: ["O"] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Preiselbeeren", amount: 50, unit: "g", allergens: [] },
      { name: "Wacholderbeeren", amount: 5, unit: "Stk", allergens: [] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Rehfleisch in Würfel schneiden und scharf anbraten",
      "Gemüse und Zwiebeln mitrösten",
      "Mit Rotwein ablöschen, Gewürze zugeben",
      "Bei 160°C 90 Minuten schmoren",
      "Sauce abseihen, Schlagobers einrühren",
      "Mit Preiselbeeren und Spätzle servieren",
    ],
    allergens: ["G", "L", "O"],
  },

  // ══════════════════════════════════════════════════
  // GULASCH & RAGOUTS (10)
  // ══════════════════════════════════════════════════
  "Rindsgulasch": {
    ingredients: [
      { name: "Rindfleisch (Wadschinken)", amount: 800, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 600, unit: "g", allergens: [] },
      { name: "Paprikapulver edelsüß", amount: 3, unit: "EL", allergens: [] },
      { name: "Tomatenmark", amount: 2, unit: "EL", allergens: [] },
      { name: "Essig", amount: 2, unit: "EL", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Zwiebeln in feine Würfel schneiden und in Schmalz goldbraun rösten",
      "Paprikapulver einrühren, SOFORT mit Essig ablöschen (verbrennt sonst!)",
      "Fleischwürfel zugeben und anbraten",
      "Tomatenmark, Kümmel und Knoblauch einrühren",
      "Wenig Wasser zugeben, 2 Stunden bei niedriger Hitze schmoren",
      "Sauce soll dicklich sein — nicht zu viel Flüssigkeit!",
    ],
    allergens: [],
  },
  "Saftgulasch": {
    ingredients: [
      { name: "Rindfleisch (Wade)", amount: 800, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 800, unit: "g", allergens: [] },
      { name: "Paprikapulver edelsüß", amount: 3, unit: "EL", allergens: [] },
      { name: "Tomatenmark", amount: 2, unit: "EL", allergens: [] },
      { name: "Essig", amount: 2, unit: "EL", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Majoran", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Zwiebeln (gleiche Menge wie Fleisch!) fein hacken, goldbraun rösten",
      "Paprika einrühren, mit Essig ablöschen",
      "Fleischwürfel zugeben, Tomatenmark einrühren",
      "Knapp mit Wasser bedecken, Kümmel und Majoran zugeben",
      "2.5 Stunden sanft schmoren bis die Sauce sämig bindet",
      "Viel Sauce — daher 'Saftgulasch'! Mit Semmelknödel servieren",
    ],
    allergens: [],
  },
  "Fiakergulasch": {
    ingredients: [
      { name: "Rindsgulasch (fertig)", amount: 800, unit: "g", allergens: [] },
      { name: "Frankfurter Würstel", amount: 4, unit: "Stk", allergens: [] },
      { name: "Eier", amount: 4, unit: "Stk", allergens: ["C"] },
      { name: "Gewürzgurken (Fächer)", amount: 4, unit: "Stk", allergens: [] },
      { name: "Semmelknödel", amount: 4, unit: "Stk", allergens: ["A", "C", "G"] },
    ],
    steps: [
      "Rindsgulasch nach Grundrezept zubereiten",
      "Frankfurter Würstel warm machen",
      "Spiegeleier braten",
      "Gulasch anrichten: Knödel, Gulasch, Würstel, Spiegelei, Gurkenfächer",
      "Das traditionelle Wiener Fiakermahl komplett servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Kalbsrahmgeschnetzeltes": {
    ingredients: [
      { name: "Kalbfleisch (Schulter)", amount: 600, unit: "g", allergens: [] },
      { name: "Champignons", amount: 200, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Weißwein", amount: 100, unit: "ml", allergens: ["O"] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 1, unit: "EL", allergens: ["A"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kalbfleisch in feine Streifen schneiden",
      "In Butter bei starker Hitze kurz anbraten, herausnehmen",
      "Champignons und Zwiebel im Bratfett anbraten",
      "Mit Mehl bestäuben, mit Weißwein ablöschen",
      "Schlagobers zugeben und einkochen lassen",
      "Fleisch zurückgeben, kurz erwärmen — nicht mehr kochen!",
    ],
    allergens: ["A", "G", "O"],
  },
  "Zürcher Geschnetzeltes": {
    ingredients: [
      { name: "Kalbfleisch", amount: 600, unit: "g", allergens: [] },
      { name: "Champignons", amount: 200, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Weißwein", amount: 100, unit: "ml", allergens: ["O"] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Zitronensaft", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kalbfleisch in dünne Streifen schneiden",
      "Portionsweise in heißer Butter scharf anbraten, herausnehmen",
      "Champignons und Zwiebel anbraten, mit Weißwein ablöschen",
      "Schlagobers zugeben, 5 Minuten einkochen",
      "Fleisch zurück, mit Zitronensaft abschmecken",
      "Klassisch mit Rösti servieren",
    ],
    allergens: ["G", "O"],
  },
  "Putengeschnetzeltes": {
    ingredients: [
      { name: "Putenbrustfilet", amount: 600, unit: "g", allergens: [] },
      { name: "Paprika bunt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Currypulver", amount: 1, unit: "EL", allergens: [] },
      { name: "Öl", amount: 3, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Putenfilet in Streifen schneiden, salzen und pfeffern",
      "In heißem Öl scharf anbraten, herausnehmen",
      "Paprika und Zwiebel im Bratfett anbraten",
      "Curry einrühren, Schlagobers zugeben",
      "5 Minuten einkochen, Fleisch zurückgeben",
      "Kurz erhitzen und mit Reis servieren",
    ],
    allergens: ["G"],
  },
  "Hühnergeschnetzeltes": {
    ingredients: [
      { name: "Hühnerbrustfilet", amount: 600, unit: "g", allergens: [] },
      { name: "Champignons", amount: 150, unit: "g", allergens: [] },
      { name: "Paprika", amount: 1, unit: "Stk", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Senf", amount: 1, unit: "TL", allergens: ["M"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Hühnerbrust in Streifen schneiden",
      "In Butter scharf anbraten, herausnehmen",
      "Gemüse und Champignons anbraten",
      "Senf einrühren, Schlagobers zugeben",
      "Fleisch zurück, kurz erwärmen",
      "Mit Spätzle oder Reis servieren",
    ],
    allergens: ["G", "M"],
  },
  "Boeuf Stroganoff": {
    ingredients: [
      { name: "Rindsfilet / Lungenbraten", amount: 600, unit: "g", allergens: [] },
      { name: "Champignons", amount: 200, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Essiggurken", amount: 3, unit: "Stk", allergens: [] },
      { name: "Sauerrahm", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Senf", amount: 1, unit: "EL", allergens: ["M"] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Paprikapulver", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Rindfleisch in dünne Streifen schneiden",
      "In heißer Butter portionsweise scharf anbraten",
      "Zwiebel und Champignons separat anbraten",
      "Essiggurken in Streifen schneiden und zugeben",
      "Sauerrahm, Senf und Paprika einrühren",
      "Fleisch zurückgeben, nur noch erwärmen — nicht kochen!",
    ],
    allergens: ["G", "M"],
  },
  "Ragout fin": {
    ingredients: [
      { name: "Kalbfleisch", amount: 300, unit: "g", allergens: [] },
      { name: "Hühnerbrustfilet", amount: 200, unit: "g", allergens: [] },
      { name: "Champignons", amount: 150, unit: "g", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Weißwein", amount: 100, unit: "ml", allergens: ["O"] },
      { name: "Eigelb", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Zitronensaft", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Kalb- und Hühnerfleisch in Brühe pochieren, würfeln",
      "Helle Einbrenn aus Butter und Mehl herstellen",
      "Mit Kochsud und Schlagobers aufgießen",
      "Champignons und Fleisch zugeben",
      "Mit Eigelb legieren, Weißwein und Zitronensaft einrühren",
      "In Blätterteigpasteten servieren",
    ],
    allergens: ["A", "C", "G", "O"],
  },
  "Kalbsgulasch": {
    ingredients: [
      { name: "Kalbfleisch (Schulter)", amount: 800, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 400, unit: "g", allergens: [] },
      { name: "Paprikapulver edelsüß", amount: 2, unit: "EL", allergens: [] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Tomatenmark", amount: 1, unit: "EL", allergens: [] },
      { name: "Zitronenschale", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Zwiebeln in Butter goldgelb rösten (nicht zu dunkel)",
      "Paprikapulver einrühren, sofort Fleisch zugeben",
      "Tomatenmark und Zitronenschale zugeben",
      "Bei niedriger Hitze 90 Minuten schmoren",
      "Schlagobers einrühren, abschmecken",
      "Heller und milder als Rindsgulasch, mit Nockerln servieren",
    ],
    allergens: ["G"],
  },

  // ══════════════════════════════════════════════════
  // GEBRATEN & GEGRILLT (15)
  // ══════════════════════════════════════════════════
  "Fleischlaberl": {
    ingredients: [
      { name: "Faschiertes gemischt", amount: 500, unit: "g", allergens: [] },
      { name: "Semmel altbacken", amount: 1, unit: "Stk", allergens: ["A"] },
      { name: "Ei", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Majoran", amount: 1, unit: "TL", allergens: [] },
      { name: "Senf", amount: 1, unit: "TL", allergens: ["M"] },
      { name: "Öl", amount: 4, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Semmel einweichen und ausdrücken",
      "Zwiebel fein hacken und anschwitzen",
      "Alle Zutaten verkneten, 15 Minuten rasten lassen",
      "Flache Laibchen formen",
      "In Öl beidseitig goldbraun braten (je 4-5 Min)",
      "Mit Erdäpfelpüree und Salat servieren",
    ],
    allergens: ["A", "C", "M"],
  },
  "Leberkäse": {
    ingredients: [
      { name: "Leberkäse (vom Fleischer)", amount: 800, unit: "g", allergens: [] },
    ],
    steps: [
      "Leberkäse in 1.5 cm dicke Scheiben schneiden",
      "In heißer Pfanne ohne Fett beidseitig goldbraun braten",
      "Mit Spiegelei, Senf und Erdäpfelsalat servieren",
    ],
    allergens: [],
  },
  "Hühnerkeule überbacken": {
    ingredients: [
      { name: "Hühnerkeulen", amount: 4, unit: "Stk", allergens: [] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Käse gerieben", amount: 80, unit: "g", allergens: ["G"] },
      { name: "Semmelbrösel", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Paprikapulver", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Hühnerkeulen salzen, pfeffern und mit Paprika einreiben",
      "Bei 180°C 30 Minuten vorgaren",
      "Käse-Semmelbrösel-Mischung daraufgeben",
      "Schlagobers angießen, weitere 15 Minuten überbacken",
      "Servieren wenn Kruste goldbraun ist",
    ],
    allergens: ["A", "G"],
  },
  "Hühnerkeule gegrillt": {
    ingredients: [
      { name: "Hühnerkeulen", amount: 4, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 3, unit: "EL", allergens: [] },
      { name: "Paprikapulver", amount: 1, unit: "EL", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Zitronensaft", amount: 2, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Marinade aus Öl, Paprika, Knoblauch und Zitrone mischen",
      "Keulen damit einreiben, 2 Stunden marinieren",
      "Bei 200°C im Ofen 40-45 Minuten grillen",
      "Regelmäßig mit Marinade bestreichen",
      "Servieren wenn Haut knusprig und Saft klar ist",
    ],
    allergens: [],
  },
  "Cevapcici": {
    ingredients: [
      { name: "Rindsfaschiertes", amount: 300, unit: "g", allergens: [] },
      { name: "Lammfaschiertes", amount: 200, unit: "g", allergens: [] },
      { name: "Knoblauch", amount: 3, unit: "Stk", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Paprikapulver", amount: 1, unit: "TL", allergens: [] },
      { name: "Natron", amount: 0.5, unit: "TL", allergens: [] },
      { name: "Ajvar", amount: 2, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Faschiertes mit Knoblauch, Zwiebel, Paprika und Natron verkneten",
      "Mindestens 2 Stunden (besser über Nacht) kalt stellen",
      "Zu fingerdicken Röllchen formen (ca. 8 cm)",
      "Auf dem Grill oder in der Pfanne rundherum braten",
      "Mit Ajvar, Zwiebeln und Fladenbrot servieren",
    ],
    allergens: [],
  },
  "Grillhendl": {
    ingredients: [
      { name: "Ganzes Huhn", amount: 1, unit: "Stk", allergens: [] },
      { name: "Paprikapulver", amount: 1, unit: "EL", allergens: [] },
      { name: "Knoblauch", amount: 3, unit: "Stk", allergens: [] },
      { name: "Öl", amount: 3, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Huhn innen und außen salzen, mit Paprika und Knoblauch einreiben",
      "Mit Öl einstreichen",
      "Bei 200°C auf dem Rost 60-75 Minuten braten",
      "Regelmäßig mit Bratfett begießen",
      "Huhn teilen und mit Pommes oder Salat servieren",
    ],
    allergens: [],
  },
  "Putenmedaillons": {
    ingredients: [
      { name: "Putenbrustfilet", amount: 600, unit: "g", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Preiselbeeren", amount: 2, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Putenbrust in 2 cm dicke Medaillons schneiden",
      "Salzen, pfeffern und in Butter beidseitig goldbraun braten",
      "Herausnehmen, Bratfond mit Schlagobers ablöschen",
      "Einkochen lassen, Preiselbeeren einrühren",
      "Medaillons mit Sauce servieren",
    ],
    allergens: ["G"],
  },
  "Saltimbocca": {
    ingredients: [
      { name: "Kalbsschnitzel dünn", amount: 4, unit: "Stk", allergens: [] },
      { name: "Parmaschinken", amount: 4, unit: "Scheiben", allergens: [] },
      { name: "Salbeiblätter", amount: 8, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Weißwein", amount: 100, unit: "ml", allergens: ["O"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Salbeiblätter auf die Schnitzel legen, Schinken darüber",
      "Mit Zahnstochern fixieren",
      "Schinkenseite zuerst in Butter braten (2 Min)",
      "Wenden und weitere 2 Minuten braten",
      "Herausnehmen, mit Weißwein ablöschen, Sauce einkochen",
      "Medaillons mit Salbei-Butter-Sauce servieren",
    ],
    allergens: ["G", "O"],
  },
  "Beuschel": {
    ingredients: [
      { name: "Kalbslunge", amount: 400, unit: "g", allergens: [] },
      { name: "Kalbsherz", amount: 200, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Essig", amount: 3, unit: "EL", allergens: [] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Mehl", amount: 20, unit: "g", allergens: ["A"] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Kapern", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Lunge und Herz in Wasser mit Lorbeer und Essig weich kochen (60 Min)",
      "Herausnehmen und in feine Streifen schneiden",
      "Helle Einbrenn machen, mit Kochsud aufgießen",
      "Innereien und Kapern zugeben, Schlagobers einrühren",
      "Mit Essig pikant abschmecken",
      "Mit Semmelknödel servieren",
    ],
    allergens: ["A", "G"],
  },
  "Beuscherl": {
    ingredients: [
      { name: "Kalbslunge", amount: 400, unit: "g", allergens: [] },
      { name: "Kalbsherz", amount: 200, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Essig", amount: 3, unit: "EL", allergens: [] },
      { name: "Sauerrahm", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Mehl", amount: 20, unit: "g", allergens: ["A"] },
      { name: "Senf", amount: 1, unit: "TL", allergens: ["M"] },
      { name: "Lorbeerblatt", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Innereien in Essigwasser weich kochen, fein schneiden",
      "Einbrenn herstellen, mit Kochsud aufgießen",
      "Innereien, Sauerrahm und Senf einrühren",
      "Pikant mit Essig abschmecken",
      "Mit Knödeln servieren",
    ],
    allergens: ["A", "G", "M"],
  },
  "Kalbsleber Berliner Art": {
    ingredients: [
      { name: "Kalbsleber", amount: 500, unit: "g", allergens: [] },
      { name: "Äpfel", amount: 2, unit: "Stk", allergens: [] },
      { name: "Zwiebeln", amount: 3, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Leber in Scheiben schneiden, Häutchen entfernen",
      "Zwiebeln in Ringe schneiden und in Butter goldbraun braten",
      "Äpfel in Ringe schneiden und kurz mitbraten, alles warmhalten",
      "Leber in Mehl wenden und in Butter kurz braten (innen noch rosa!)",
      "Mit Äpfeln und Zwiebeln anrichten",
      "Mit Kartoffelpüree servieren",
    ],
    allergens: ["A", "G"],
  },
  "Blunzengröstl": {
    ingredients: [
      { name: "Blutwurst (Blunzen)", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln gekocht", amount: 500, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 2, unit: "Stk", allergens: [] },
      { name: "Schmalz", amount: 40, unit: "g", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Majoran", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffeln in Scheiben schneiden",
      "Blunzen in Scheiben schneiden",
      "Zwiebeln in Schmalz goldbraun rösten",
      "Kartoffeln zugeben und knusprig braten",
      "Blunzen vorsichtig unterheben (zerfällt leicht)",
      "Mit Kümmel und Majoran würzen, mit Sauerkraut servieren",
    ],
    allergens: [],
  },
  "Tiroler Gröstl": {
    ingredients: [
      { name: "Rindfleisch (gekocht, vom Vortag)", amount: 300, unit: "g", allergens: [] },
      { name: "Kartoffeln gekocht", amount: 500, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 2, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Eier (Spiegelei)", amount: 4, unit: "Stk", allergens: ["C"] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffeln und Fleisch in Scheiben schneiden",
      "Zwiebeln in Butter goldbraun rösten",
      "Kartoffeln zugeben und knusprig braten",
      "Fleisch untermischen, mit Kümmel würzen",
      "Spiegeleier separat braten",
      "Gröstl mit Spiegelei und Petersilie servieren",
    ],
    allergens: ["C", "G"],
  },
  "Bauernschmaus": {
    ingredients: [
      { name: "Selchfleisch", amount: 300, unit: "g", allergens: [] },
      { name: "Schweinsbraten", amount: 300, unit: "g", allergens: [] },
      { name: "Frankfurter Würstel", amount: 4, unit: "Stk", allergens: [] },
      { name: "Sauerkraut", amount: 500, unit: "g", allergens: ["O"] },
      { name: "Semmelknödel", amount: 4, unit: "Stk", allergens: ["A", "C", "G"] },
      { name: "Braterdäpfel", amount: 300, unit: "g", allergens: [] },
    ],
    steps: [
      "Selchfleisch in Wasser kochen",
      "Sauerkraut mit Kümmel und Wacholder dünsten",
      "Schweinsbraten aufwärmen, Würstel warm machen",
      "Semmelknödel kochen, Erdäpfel braten",
      "Alles auf einer großen Platte anrichten",
      "Mit Senf und Kren servieren",
    ],
    allergens: ["A", "C", "G", "O"],
  },
  "Krainer Würstel": {
    ingredients: [
      { name: "Krainer Würstel", amount: 4, unit: "Stk", allergens: [] },
      { name: "Senf scharf", amount: 3, unit: "EL", allergens: ["M"] },
      { name: "Kren frisch", amount: 30, unit: "g", allergens: [] },
    ],
    steps: [
      "Krainer in heißem (nicht kochendem!) Wasser 15 Minuten ziehen lassen",
      "Oder: Auf dem Grill rundherum bräunen",
      "Mit Senf und frisch geriebenem Kren servieren",
      "Dazu Gebäck oder Brot reichen",
    ],
    allergens: ["M"],
  },

  // ══════════════════════════════════════════════════
  // FISCH (15)
  // ══════════════════════════════════════════════════
  "Gebratenes Forellenfilet": {
    ingredients: [
      { name: "Forellenfilet", amount: 4, unit: "Stk", allergens: ["D"] },
      { name: "Mehl", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Forellenfilets salzen, pfeffern und in Mehl wenden",
      "In heißer Butter Hautseite zuerst 3 Minuten braten",
      "Wenden und weitere 2 Minuten braten",
      "Butter in der Pfanne nussbraun werden lassen",
      "Mit Zitronensaft und Petersilie servieren",
    ],
    allergens: ["A", "D", "G"],
  },
  "Zanderfilet": {
    ingredients: [
      { name: "Zanderfilet", amount: 4, unit: "Stk", allergens: ["D"] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Weißwein", amount: 100, unit: "ml", allergens: ["O"] },
      { name: "Dill", amount: 1, unit: "Bund", allergens: [] },
      { name: "Zitronensaft", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zanderfilets salzen und pfeffern",
      "Hautseite in heißer Butter knusprig braten (3-4 Min)",
      "Wenden, 2 Minuten weiterbraten",
      "Herausnehmen, Bratfond mit Weißwein ablöschen",
      "Butter und Zitronensaft einrühren",
      "Mit Dill und Sauce servieren",
    ],
    allergens: ["D", "G", "O"],
  },
  "Lachsfilet": {
    ingredients: [
      { name: "Lachsfilet", amount: 4, unit: "Stk", allergens: ["D"] },
      { name: "Olivenöl", amount: 2, unit: "EL", allergens: [] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
      { name: "Dill", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Lachsfilets salzen und pfeffern",
      "In heißem Olivenöl Hautseite zuerst 4 Minuten braten",
      "Wenden und 2-3 Minuten weiterbraten (innen glasig)",
      "Mit Zitronensaft beträufeln und Dill garnieren",
    ],
    allergens: ["D"],
  },
  "Fischstäbchen": {
    ingredients: [
      { name: "Fischstäbchen (TK)", amount: 20, unit: "Stk", allergens: ["A", "D"] },
      { name: "Öl zum Braten", amount: 4, unit: "EL", allergens: [] },
    ],
    steps: [
      "Fischstäbchen tiefgekühlt in heißem Öl goldbraun braten",
      "Je Seite 3-4 Minuten bei mittlerer Hitze",
      "Oder im Ofen bei 200°C 15-18 Minuten backen",
      "Mit Kartoffelpüree und Zitrone servieren",
    ],
    allergens: ["A", "D"],
  },
  "Schollenfilet": {
    ingredients: [
      { name: "Schollenfilet", amount: 4, unit: "Stk", allergens: ["D"] },
      { name: "Mehl", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Schollenfilets salzen, pfeffern und leicht in Mehl wenden",
      "In heißer Butter beidseitig je 2-3 Minuten braten",
      "Butter nussbraun werden lassen (Meunière)",
      "Mit Zitrone und Petersilie servieren",
    ],
    allergens: ["A", "D", "G"],
  },
  "Kabeljau gebacken": {
    ingredients: [
      { name: "Kabeljaufilet", amount: 600, unit: "g", allergens: ["D"] },
      { name: "Mehl", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 100, unit: "g", allergens: ["A"] },
      { name: "Öl zum Frittieren", amount: 500, unit: "ml", allergens: [] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kabeljau in Portionsstücke schneiden, salzen",
      "Panieren: Mehl, Ei, Semmelbrösel",
      "Bei 170°C goldbraun frittieren (ca. 5 Min)",
      "Auf Küchenpapier abtropfen",
      "Mit Zitrone und Remoulade servieren",
    ],
    allergens: ["A", "C", "D"],
  },
  "Seelachsfilet": {
    ingredients: [
      { name: "Seelachsfilet", amount: 4, unit: "Stk", allergens: ["D"] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
      { name: "Dill", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Filets salzen und pfeffern",
      "In heißer Butter beidseitig goldbraun braten",
      "Mit Zitronensaft beträufeln",
      "Mit Dill garniert servieren",
    ],
    allergens: ["D", "G"],
  },
  "Dorschfilet": {
    ingredients: [
      { name: "Dorschfilet", amount: 4, unit: "Stk", allergens: ["D"] },
      { name: "Olivenöl", amount: 3, unit: "EL", allergens: [] },
      { name: "Kirschtomaten", amount: 200, unit: "g", allergens: [] },
      { name: "Oliven schwarz", amount: 50, unit: "g", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Basilikum", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Dorschfilets salzen und pfeffern",
      "In Olivenöl beidseitig anbraten",
      "Tomaten, Oliven und Knoblauch zugeben",
      "10 Minuten bei mittlerer Hitze garen",
      "Mit Basilikum servieren",
    ],
    allergens: ["D"],
  },
  "Fischknusperle": {
    ingredients: [
      { name: "Fischfilet (Seelachs)", amount: 500, unit: "g", allergens: ["D"] },
      { name: "Backteig (Mehl, Bier, Ei)", amount: 200, unit: "g", allergens: ["A", "C"] },
      { name: "Öl zum Frittieren", amount: 500, unit: "ml", allergens: [] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Fisch in mundgerechte Stücke schneiden, salzen",
      "Backteig aus Mehl, Bier und Ei anrühren",
      "Fischstücke durch den Teig ziehen",
      "Bei 170°C goldbraun frittieren (3-4 Min)",
      "Auf Küchenpapier abtropfen, mit Zitrone servieren",
    ],
    allergens: ["A", "C", "D"],
  },
  "Pangasiusfilet": {
    ingredients: [
      { name: "Pangasiusfilet", amount: 4, unit: "Stk", allergens: ["D"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Zitronensaft", amount: 2, unit: "EL", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Filets salzen, pfeffern und mit Zitrone beträufeln",
      "In Butter beidseitig goldbraun braten (je 3 Min)",
      "Mit Petersilie bestreuen und servieren",
    ],
    allergens: ["D", "G"],
  },
  "Forelle Müllerin": {
    ingredients: [
      { name: "Ganze Forelle", amount: 4, unit: "Stk", allergens: ["D"] },
      { name: "Mehl", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Butter", amount: 80, unit: "g", allergens: ["G"] },
      { name: "Zitrone", amount: 1, unit: "Stk", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Forellen innen und außen salzen",
      "In Mehl wenden (Müllerin = 'nach Müllerinart')",
      "In heißer Butter beidseitig goldbraun braten (je 5 Min)",
      "Butter in der Pfanne nussbraun werden lassen",
      "Mit Nussbutter, Zitrone und Petersilie servieren",
    ],
    allergens: ["A", "D", "G"],
  },
  "Karpfen blau": {
    ingredients: [
      { name: "Karpfen ganz", amount: 1, unit: "Stk", allergens: ["D"] },
      { name: "Essig", amount: 100, unit: "ml", allergens: [] },
      { name: "Suppengemüse", amount: 200, unit: "g", allergens: ["L"] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Pfefferkörner", amount: 5, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Karpfen NICHT schuppen — die Schleimschicht wird blau durch den Essig",
      "Sud aus Wasser, Essig, Suppengemüse und Gewürzen aufsetzen",
      "Karpfen vorsichtig einlegen",
      "Bei 70-80°C 20-25 Minuten ziehen lassen (nie kochen!)",
      "Mit zerlassener Butter und Petersilkartoffeln servieren",
    ],
    allergens: ["D", "L"],
  },
  "Matjesfilet": {
    ingredients: [
      { name: "Matjesfilet", amount: 8, unit: "Stk", allergens: ["D"] },
      { name: "Sauerrahm", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Zwiebel rot", amount: 1, unit: "Stk", allergens: [] },
      { name: "Äpfel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Dill", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Matjesfilets auf einer Platte anrichten",
      "Zwiebel in feine Ringe, Apfel in Spalten schneiden",
      "Sauerrahm mit Dill verrühren",
      "Alles zusammen anrichten",
      "Mit Bratkartoffeln servieren",
    ],
    allergens: ["D", "G"],
  },
  "Thunfischsteak": {
    ingredients: [
      { name: "Thunfischsteak", amount: 4, unit: "Stk", allergens: ["D"] },
      { name: "Olivenöl", amount: 3, unit: "EL", allergens: [] },
      { name: "Sojasauce", amount: 2, unit: "EL", allergens: ["F"] },
      { name: "Sesam", amount: 2, unit: "EL", allergens: ["N"] },
      { name: "Ingwer", amount: 10, unit: "g", allergens: [] },
      { name: "Limette", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Thunfischsteaks in Sojasauce und Ingwer 30 Minuten marinieren",
      "In Sesam wenden",
      "In sehr heißem Öl je Seite 1-2 Minuten braten (innen rosa!)",
      "Mit Limettenspalten servieren",
    ],
    allergens: ["D", "F", "N"],
  },
  "Garnelenpfanne": {
    ingredients: [
      { name: "Garnelen (geschält)", amount: 500, unit: "g", allergens: ["B"] },
      { name: "Knoblauch", amount: 4, unit: "Stk", allergens: [] },
      { name: "Chilischote", amount: 1, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 4, unit: "EL", allergens: [] },
      { name: "Weißwein", amount: 100, unit: "ml", allergens: ["O"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Zitronensaft", amount: 2, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Knoblauch in Scheiben und Chili in Ringe schneiden",
      "In Olivenöl bei starker Hitze anbraten",
      "Garnelen zugeben und 2-3 Minuten braten bis rosa",
      "Mit Weißwein ablöschen, Zitronensaft zugeben",
      "Mit Petersilie bestreuen und sofort servieren",
    ],
    allergens: ["B", "O"],
  },
};
