/**
 * Soup recipe completion data — 65 soups (CreamSoups + ClearSoups)
 * Allergen Codes: A=Gluten B=Krebstiere C=Eier D=Fisch E=Erdnüsse
 * F=Soja G=Milch H=Schalenfrüchte L=Sellerie M=Senf
 * N=Sesam O=Sulfite P=Lupinen R=Weichtiere
 */
import type { RecipeCompletionMap } from "../complete-recipes";

export const SOUP_DATA: RecipeCompletionMap = {
  // ══════════════════════════════════════════════════
  // CREMESUPPEN (20)
  // ══════════════════════════════════════════════════
  "Spargelcremesuppe": {
    ingredients: [
      { name: "Spargel weiß", amount: 500, unit: "g", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Spargel schälen, holzige Enden abschneiden und in Stücke schneiden",
      "Zwiebel fein würfeln und in Butter glasig anschwitzen",
      "Mit Mehl bestäuben und kurz anschwitzen (Einbrenn)",
      "Mit Gemüsebrühe aufgießen und Spargel zugeben",
      "20 Minuten weich kochen, dann fein pürieren",
      "Schlagobers einrühren, mit Salz und Muskatnuss abschmecken",
    ],
    allergens: ["A", "G", "L"],
  },
  "Selleriecremesuppe": {
    ingredients: [
      { name: "Knollensellerie", amount: 400, unit: "g", allergens: ["L"] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Sellerie und Kartoffeln schälen und würfeln",
      "Zwiebel in Butter anschwitzen, Sellerie und Kartoffeln zugeben",
      "Mit Gemüsebrühe aufgießen und 25 Minuten weich kochen",
      "Fein pürieren und Schlagobers einrühren",
      "Mit Salz und Pfeffer abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Kürbiscremesuppe": {
    ingredients: [
      { name: "Hokkaido-Kürbis", amount: 600, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Ingwer", amount: 10, unit: "g", allergens: [] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Kürbiskernöl", amount: 2, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kürbis entkernen und in Würfel schneiden (Hokkaido mit Schale)",
      "Zwiebel und Ingwer fein hacken und in Öl anschwitzen",
      "Kürbis und Kartoffeln zugeben, mit Gemüsebrühe aufgießen",
      "20 Minuten weich kochen, dann fein pürieren",
      "Schlagobers einrühren, mit Salz abschmecken",
      "Mit einem Schuss Kürbiskernöl servieren",
    ],
    allergens: ["G", "L"],
  },
  "Knoblauchcremesuppe": {
    ingredients: [
      { name: "Knoblauch", amount: 80, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Weißbrot", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Knoblauchzehen schälen und grob hacken",
      "In Butter bei niedriger Hitze anschwitzen (nicht bräunen!)",
      "Kartoffeln und Weißbrot zugeben, mit Gemüsebrühe aufgießen",
      "20 Minuten köcheln, dann fein pürieren",
      "Schlagobers einrühren und abschmecken",
    ],
    allergens: ["A", "G", "L"],
  },
  "Bärlauchcremesuppe": {
    ingredients: [
      { name: "Bärlauch frisch", amount: 150, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Bärlauch waschen und grob schneiden",
      "Zwiebel in Butter anschwitzen, Kartoffeln zugeben",
      "Mit Gemüsebrühe aufgießen, 15 Minuten kochen",
      "Bärlauch zugeben und sofort pürieren (Farbe erhalten)",
      "Schlagobers einrühren und abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Karottencremesuppe": {
    ingredients: [
      { name: "Karotten", amount: 500, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Ingwer", amount: 5, unit: "g", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Karotten und Kartoffeln schälen und in Stücke schneiden",
      "Zwiebel und Ingwer in Butter anschwitzen",
      "Gemüse zugeben, mit Brühe aufgießen, 20 Minuten kochen",
      "Fein pürieren, Schlagobers einrühren",
      "Mit Salz abschmecken, eventuell mit Croutons servieren",
    ],
    allergens: ["G", "L"],
  },
  "Brokkolicremesuppe": {
    ingredients: [
      { name: "Brokkoli", amount: 500, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Brokkoli in Röschen teilen, Stiel schälen und würfeln",
      "Zwiebel in Butter anschwitzen, Kartoffeln und Brokkolistiel zugeben",
      "Mit Brühe aufgießen, 10 Min kochen, dann Röschen zugeben",
      "Weitere 8 Minuten kochen, fein pürieren",
      "Schlagobers und Muskatnuss einrühren, abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Blumenkohlcremesuppe": {
    ingredients: [
      { name: "Blumenkohl", amount: 500, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Blumenkohl in Röschen teilen, Kartoffeln würfeln",
      "In Butter kurz anschwitzen, mit Brühe aufgießen",
      "20 Minuten weich kochen, fein pürieren",
      "Schlagobers einrühren, mit Muskatnuss und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Tomatencremesuppe": {
    ingredients: [
      { name: "Tomaten", amount: 600, unit: "g", allergens: [] },
      { name: "Tomatenmark", amount: 30, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 600, unit: "ml", allergens: ["L"] },
      { name: "Basilikum", amount: 1, unit: "Bund", allergens: [] },
      { name: "Zucker", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Tomaten kreuzweise einritzen, überbrühen und häuten",
      "Zwiebel und Knoblauch in Butter anschwitzen",
      "Tomatenmark kurz mitrösten, Tomaten zugeben",
      "Mit Gemüsebrühe aufgießen, 20 Minuten köcheln",
      "Pürieren, Schlagobers und Basilikum einrühren",
      "Mit Zucker und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Zucchinicremesuppe": {
    ingredients: [
      { name: "Zucchini", amount: 500, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Basilikum", amount: 4, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zucchini waschen und in Stücke schneiden, Kartoffeln würfeln",
      "Zwiebel in Butter anschwitzen, Gemüse zugeben",
      "Mit Brühe aufgießen, 15 Minuten kochen",
      "Pürieren, Schlagobers und Basilikum einrühren",
      "Mit Salz und Pfeffer abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Paprikacremesuppe": {
    ingredients: [
      { name: "Paprika rot", amount: 500, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Paprikapulver edelsüß", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Paprika entkernen und in Stücke schneiden",
      "Zwiebel und Knoblauch in Butter anschwitzen",
      "Paprika und Kartoffeln zugeben, Paprikapulver einrühren",
      "Mit Brühe aufgießen, 20 Minuten kochen",
      "Fein pürieren, Schlagobers einrühren, abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Champignoncremesuppe": {
    ingredients: [
      { name: "Champignons", amount: 400, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 600, unit: "ml", allergens: ["L"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Champignons putzen und blättrig schneiden",
      "Zwiebel in Butter anschwitzen, Champignons zugeben und mitbraten",
      "Mit Mehl bestäuben, kurz anschwitzen",
      "Mit Brühe ablöschen, 15 Minuten köcheln",
      "Teilweise pürieren (etwas Stückigkeit behalten)",
      "Schlagobers einrühren, mit Petersilie garnieren",
    ],
    allergens: ["A", "G", "L"],
  },
  "Erbsencremesuppe": {
    ingredients: [
      { name: "Erbsen tiefgekühlt", amount: 500, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Minze", amount: 4, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebel in Butter anschwitzen, Kartoffeln zugeben",
      "Mit Brühe aufgießen, 10 Minuten kochen",
      "Erbsen zugeben, weitere 5 Minuten kochen",
      "Fein pürieren, Schlagobers und Minze einrühren",
      "Mit Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Fenchelcremesuppe": {
    ingredients: [
      { name: "Fenchel", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Pernod", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Fenchel putzen und in Stücke schneiden, Grün aufheben",
      "Zwiebel in Butter anschwitzen, Fenchel und Kartoffeln zugeben",
      "Mit Brühe aufgießen, 20 Minuten weich kochen",
      "Pürieren, Schlagobers und einen Schuss Pernod einrühren",
      "Mit Salz abschmecken, mit Fenchelgrün garnieren",
    ],
    allergens: ["G", "L"],
  },
  "Maiscremesuppe": {
    ingredients: [
      { name: "Mais (Dose oder TK)", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 600, unit: "ml", allergens: ["L"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebel in Butter anschwitzen",
      "Mais und Kartoffeln zugeben, mit Brühe aufgießen",
      "15 Minuten kochen, fein pürieren",
      "Schlagobers einrühren, mit Salz und Pfeffer abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Kartoffelcremesuppe": {
    ingredients: [
      { name: "Kartoffeln mehlig", amount: 500, unit: "g", allergens: [] },
      { name: "Lauch", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffeln schälen und würfeln, Lauch in Ringe schneiden",
      "Zwiebel in Butter anschwitzen, Lauch kurz mitdünsten",
      "Kartoffeln zugeben, mit Brühe aufgießen, 20 Minuten kochen",
      "Pürieren, Schlagobers einrühren",
      "Mit Muskatnuss und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Lauchcremesuppe": {
    ingredients: [
      { name: "Lauch", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Lauch längs halbieren, waschen und in Ringe schneiden",
      "In Butter anschwitzen, Kartoffeln zugeben",
      "Mit Brühe aufgießen, 20 Minuten kochen",
      "Pürieren, Schlagobers einrühren, abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Spinatcremesuppe": {
    ingredients: [
      { name: "Blattspinat", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebel und Knoblauch in Butter anschwitzen",
      "Kartoffeln zugeben, mit Brühe aufgießen, 15 Minuten kochen",
      "Spinat zugeben und zusammenfallen lassen",
      "Fein pürieren, Schlagobers einrühren",
      "Mit Muskatnuss und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Kohlrabicremesuppe": {
    ingredients: [
      { name: "Kohlrabi", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kohlrabi schälen und würfeln, zarte Blätter aufheben",
      "Zwiebel in Butter anschwitzen, Kohlrabi und Kartoffeln zugeben",
      "Mit Brühe aufgießen, 20 Minuten weich kochen",
      "Pürieren, Schlagobers einrühren, abschmecken",
      "Mit gehackten Kohlrabiblättern garnieren",
    ],
    allergens: ["G", "L"],
  },
  "Rote-Rüben-Cremesuppe": {
    ingredients: [
      { name: "Rote Rüben gekocht", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Kren frisch gerieben", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebel in Butter anschwitzen",
      "Rote Rüben und Kartoffeln zugeben, mit Brühe aufgießen",
      "15 Minuten kochen, fein pürieren",
      "Schlagobers einrühren, mit Kren und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },

  // ══════════════════════════════════════════════════
  // KLARE SUPPEN & KLASSIKER (20)
  // ══════════════════════════════════════════════════
  "Leberknödelsuppe": {
    ingredients: [
      { name: "Rindsleber", amount: 200, unit: "g", allergens: [] },
      { name: "Semmeln (altbacken)", amount: 3, unit: "Stk", allergens: ["A"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Majoran", amount: 1, unit: "TL", allergens: [] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Leber fein faschieren oder im Blitzhacker zerkleinern",
      "Semmeln in Milch einweichen und ausdrücken",
      "Zwiebel fein würfeln und in Butter anschwitzen",
      "Alle Zutaten zu einem Teig verkneten, 30 Minuten rasten lassen",
      "Mit nassen Händen Knödel formen",
      "In siedender Rindssuppe 15 Minuten ziehen lassen (nicht kochen)",
      "Mit Schnittlauch garniert servieren",
    ],
    allergens: ["A", "C", "L"],
  },
  "Grießnockerlsuppe": {
    ingredients: [
      { name: "Grieß", amount: 100, unit: "g", allergens: ["A"] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Butter schaumig rühren, Ei einrühren",
      "Grieß und Muskatnuss unterheben, 30 Minuten im Kühlschrank rasten",
      "Mit zwei Löffeln Nockerl abstechen",
      "In siedender Rindssuppe 10-15 Minuten ziehen lassen",
      "Mit Schnittlauch servieren",
    ],
    allergens: ["A", "C", "G", "L"],
  },
  "Fritatensuppe": {
    ingredients: [
      { name: "Mehl", amount: 100, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Milch", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Aus Mehl, Eiern, Milch und Salz einen glatten Palatschinkenteig rühren",
      "Dünne Palatschinken in wenig Öl herausbacken",
      "Abkühlen lassen und in feine Streifen (Fritaten) schneiden",
      "In heißer Rindssuppe servieren",
      "Mit Schnittlauch bestreuen",
    ],
    allergens: ["A", "C", "G", "L"],
  },
  "Nudelsuppe": {
    ingredients: [
      { name: "Suppennudeln", amount: 100, unit: "g", allergens: ["A", "C"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Rindssuppe zum Kochen bringen",
      "Suppennudeln einlegen und bissfest kochen (lt. Packung)",
      "Mit Schnittlauch garniert servieren",
    ],
    allergens: ["A", "C", "L"],
  },
  "Schwammerlsuppe": {
    ingredients: [
      { name: "Gemischte Pilze", amount: 400, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 20, unit: "g", allergens: ["A"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Pilze putzen und in Scheiben schneiden",
      "Zwiebel in Butter anschwitzen, Pilze zugeben und kräftig anbraten",
      "Mit Mehl bestäuben, mit Brühe aufgießen",
      "15 Minuten köcheln, teilweise pürieren",
      "Schlagobers und Thymian einrühren, abschmecken",
    ],
    allergens: ["A", "G", "L"],
  },
  "Zwiebelsuppe": {
    ingredients: [
      { name: "Zwiebeln", amount: 500, unit: "g", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 20, unit: "g", allergens: ["A"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Weißwein", amount: 100, unit: "ml", allergens: ["O"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebeln in feine Ringe schneiden",
      "In Butter bei mittlerer Hitze goldbraun rösten (ca. 20 Min)",
      "Mit Mehl bestäuben, mit Weißwein ablöschen",
      "Rindssuppe zugeben, 20 Minuten köcheln",
      "Mit Salz und Pfeffer abschmecken",
    ],
    allergens: ["A", "G", "L", "O"],
  },
  "Erdäpfelsuppe": {
    ingredients: [
      { name: "Kartoffeln mehlig", amount: 500, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 50, unit: "g", allergens: ["L"] },
      { name: "Lauch", amount: 80, unit: "g", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Majoran", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffeln, Karotten und Sellerie schälen und würfeln",
      "Lauch in Ringe schneiden, in Butter anschwitzen",
      "Gemüse zugeben, mit Brühe aufgießen",
      "25 Minuten weich kochen, grob zerstampfen",
      "Mit Majoran und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Einmachsuppe": {
    ingredients: [
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Eigelb", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Helle Einbrenn: Butter schmelzen, Mehl einrühren, hell anschwitzen",
      "Langsam mit kalter Rindssuppe aufgießen (klümpchenfrei rühren)",
      "15 Minuten köcheln lassen",
      "Eigelb mit Schlagobers verquirlen und einrühren (nicht mehr kochen!)",
      "Mit Muskatnuss und Salz abschmecken",
    ],
    allergens: ["A", "C", "G", "L"],
  },
  "Rindssuppe klar": {
    ingredients: [
      { name: "Rindfleisch (Suppenfleisch)", amount: 500, unit: "g", allergens: [] },
      { name: "Karotten", amount: 200, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 100, unit: "g", allergens: ["L"] },
      { name: "Lauch", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Pfefferkörner", amount: 5, unit: "Stk", allergens: [] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Fleisch in kaltem Wasser aufsetzen und langsam zum Sieden bringen",
      "Schaum regelmäßig abschöpfen",
      "Suppengemüse und Gewürze zugeben",
      "Bei niedriger Hitze 2-3 Stunden köcheln lassen",
      "Durch ein feines Sieb abseihen, entfetten",
      "Mit Salz abschmecken, mit gewünschter Einlage servieren",
    ],
    allergens: ["L"],
  },
  "Backerbsensuppe": {
    ingredients: [
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Backerbsen", amount: 100, unit: "g", allergens: ["A", "C"] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Rindssuppe erhitzen",
      "In Suppenteller anrichten",
      "Backerbsen erst beim Servieren über die Suppe streuen",
      "Mit Schnittlauch garnieren",
    ],
    allergens: ["A", "C", "L"],
  },
  "Kaspressknödelsuppe": {
    ingredients: [
      { name: "Semmeln altbacken", amount: 3, unit: "Stk", allergens: ["A"] },
      { name: "Bergkäse gerieben", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Milch", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Semmeln in kleine Würfel schneiden und in Milch einweichen",
      "Zwiebel in Butter anschwitzen",
      "Semmelwürfel, Käse, Eier und Zwiebel vermengen",
      "Flache Knödel formen und in Butter goldbraun braten",
      "In heißer Rindssuppe servieren",
    ],
    allergens: ["A", "C", "G", "L"],
  },
  "Tiroler Knödelsuppe": {
    ingredients: [
      { name: "Semmeln altbacken", amount: 4, unit: "Stk", allergens: ["A"] },
      { name: "Speck geräuchert", amount: 100, unit: "g", allergens: [] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Milch", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Mehl", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Semmeln würfeln und in lauwarmer Milch einweichen",
      "Speck und Zwiebel fein würfeln und anbraten",
      "Alle Zutaten vermengen, 15 Minuten rasten lassen",
      "Knödel formen und in Salzwasser 15 Minuten ziehen lassen",
      "In heißer Rindssuppe mit Schnittlauch servieren",
    ],
    allergens: ["A", "C", "G", "L"],
  },
  "Brotsuppe": {
    ingredients: [
      { name: "Bauernbrot altbacken", amount: 200, unit: "g", allergens: ["A"] },
      { name: "Zwiebeln", amount: 2, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Brot in Scheiben schneiden und im Ofen rösten",
      "Zwiebeln in Butter goldbraun rösten",
      "Brot zugeben, mit Rindssuppe aufgießen",
      "15 Minuten köcheln, leicht zerstampfen",
      "Mit Kümmel und Schnittlauch servieren",
    ],
    allergens: ["A", "G", "L"],
  },
  "Steirische Wurzelsuppe": {
    ingredients: [
      { name: "Karotten", amount: 150, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 100, unit: "g", allergens: ["L"] },
      { name: "Pastinaken", amount: 100, unit: "g", allergens: [] },
      { name: "Petersilienwurzel", amount: 80, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Wurzelgemüse schälen und fein würfeln",
      "In Rindssuppe aufkochen, 20 Minuten weich kochen",
      "Einen Teil pürieren, Rest stückig lassen",
      "Schlagobers einrühren, mit Petersilie garnieren",
    ],
    allergens: ["G", "L"],
  },
  "Saure Suppe (Steirisch)": {
    ingredients: [
      { name: "Schweinefleisch (Schulter)", amount: 300, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 50, unit: "g", allergens: ["L"] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Sauerrahm", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Essig", amount: 3, unit: "EL", allergens: [] },
      { name: "Mehl", amount: 20, unit: "g", allergens: ["A"] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Lorbeerblatt", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Fleisch in Wasser mit Lorbeer und Kümmel weich kochen",
      "Gemüse und Kartoffeln zugeben, weiter kochen",
      "Mehl mit Sauerrahm und Essig glatt rühren",
      "In die Suppe einrühren, nochmals aufkochen",
      "Fleisch in Stücke schneiden und in der Suppe servieren",
    ],
    allergens: ["A", "G", "L"],
  },
  "Altwiener Suppentopf": {
    ingredients: [
      { name: "Rindfleisch", amount: 300, unit: "g", allergens: [] },
      { name: "Karotten", amount: 150, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 80, unit: "g", allergens: ["L"] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Erbsen", amount: 80, unit: "g", allergens: [] },
      { name: "Kohlrabi", amount: 100, unit: "g", allergens: [] },
      { name: "Rindssuppe", amount: 1200, unit: "ml", allergens: ["L"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Rindfleisch in Würfel schneiden und in Suppe weich kochen",
      "Gemüse und Kartoffeln schälen und würfeln",
      "Gemüse zur Suppe geben und garen",
      "Mit Petersilie garniert servieren",
    ],
    allergens: ["L"],
  },
  "Kalbsknochensuppe": {
    ingredients: [
      { name: "Kalbsknochen", amount: 500, unit: "g", allergens: [] },
      { name: "Karotten", amount: 150, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 80, unit: "g", allergens: ["L"] },
      { name: "Lauch", amount: 80, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Lorbeerblatt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Pfefferkörner", amount: 5, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Kalbsknochen im Ofen bei 200°C 30 Minuten rösten",
      "In einen großen Topf geben, mit kaltem Wasser auffüllen",
      "Suppengemüse und Gewürze zugeben",
      "3 Stunden bei niedriger Hitze köcheln, regelmäßig abschäumen",
      "Durch ein feines Sieb passieren, abschmecken",
    ],
    allergens: ["L"],
  },
  "Flädlesuppe": {
    ingredients: [
      { name: "Mehl", amount: 100, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Milch", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Aus Mehl, Eiern und Milch dünnen Teig rühren, 15 Min rasten",
      "Dünne Pfannkuchen (Flädle) ausbacken",
      "Auskühlen lassen und in feine Streifen schneiden",
      "In heißer Rindssuppe servieren, mit Schnittlauch bestreuen",
    ],
    allergens: ["A", "C", "G", "L"],
  },
  "Markklößchensuppe": {
    ingredients: [
      { name: "Rindermark", amount: 100, unit: "g", allergens: [] },
      { name: "Semmelbrösel", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Mark bei Zimmertemperatur weich werden lassen und cremig rühren",
      "Ei, Semmelbrösel, Petersilie und Muskatnuss einarbeiten",
      "30 Minuten im Kühlschrank rasten lassen",
      "Kleine Klößchen formen",
      "In siedender Rindssuppe 10 Minuten gar ziehen lassen",
    ],
    allergens: ["A", "C", "L"],
  },
  "Leberreissuppe": {
    ingredients: [
      { name: "Rindsleber", amount: 150, unit: "g", allergens: [] },
      { name: "Reis", amount: 80, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 20, unit: "g", allergens: ["G"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Majoran", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Leber fein hacken oder passieren",
      "Zwiebel in Butter anschwitzen, Reis zugeben und glasig rühren",
      "Leber einrühren und kurz mitbraten",
      "Mit Rindssuppe aufgießen, 20 Minuten kochen bis Reis gar",
      "Mit Majoran und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },

  // ══════════════════════════════════════════════════
  // HÜLSENFRUCHT- & EINTOPFSUPPEN (10)
  // ══════════════════════════════════════════════════
  "Linsensuppe": {
    ingredients: [
      { name: "Linsen braun", amount: 250, unit: "g", allergens: [] },
      { name: "Karotten", amount: 150, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 80, unit: "g", allergens: ["L"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Speck", amount: 50, unit: "g", allergens: [] },
      { name: "Essig", amount: 2, unit: "EL", allergens: [] },
      { name: "Gemüsebrühe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Lorbeerblatt", amount: 1, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Linsen waschen und abtropfen lassen",
      "Speck würfeln und auslassen, Zwiebel und Gemüse zugeben",
      "Linsen und Lorbeerblatt zugeben, mit Brühe aufgießen",
      "40 Minuten weich kochen",
      "Mit Essig und Salz abschmecken",
    ],
    allergens: ["L"],
  },
  "Bohnensuppe": {
    ingredients: [
      { name: "Weiße Bohnen (getrocknet)", amount: 250, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 60, unit: "g", allergens: ["L"] },
      { name: "Speck", amount: 80, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Gemüsebrühe", amount: 1200, unit: "ml", allergens: ["L"] },
      { name: "Bohnenkraut", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Bohnen über Nacht einweichen, abgießen",
      "Speck und Zwiebel anbraten, Gemüse zugeben",
      "Bohnen und Brühe zugeben, 60-90 Minuten weich kochen",
      "Einen Teil pürieren für Bindung",
      "Mit Bohnenkraut und Salz abschmecken",
    ],
    allergens: ["L"],
  },
  "Erbsensuppe": {
    ingredients: [
      { name: "Gelbe Erbsen (getrocknet)", amount: 250, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 60, unit: "g", allergens: ["L"] },
      { name: "Speck", amount: 80, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Gemüsebrühe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Majoran", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Erbsen waschen (evtl. über Nacht einweichen)",
      "Speck und Zwiebel anbraten, Gemüse zugeben",
      "Erbsen und Brühe zugeben, 60 Minuten weich kochen",
      "Teilweise pürieren, mit Majoran abschmecken",
    ],
    allergens: ["L"],
  },
  "Minestrone": {
    ingredients: [
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Zucchini", amount: 100, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 60, unit: "g", allergens: ["L"] },
      { name: "Kartoffeln", amount: 100, unit: "g", allergens: [] },
      { name: "Fisolen", amount: 80, unit: "g", allergens: [] },
      { name: "Tomaten", amount: 200, unit: "g", allergens: [] },
      { name: "Kleine Nudeln", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Olivenöl", amount: 3, unit: "EL", allergens: [] },
      { name: "Gemüsebrühe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Parmesan", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Basilikum", amount: 4, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Gemüse waschen, putzen und in kleine Würfel schneiden",
      "In Olivenöl anschwitzen, mit Brühe aufgießen",
      "15 Minuten kochen, Nudeln zugeben",
      "Weitere 10 Minuten kochen bis alles gar",
      "Mit Parmesan und Basilikum servieren",
    ],
    allergens: ["A", "G", "L"],
  },
  "Gulaschsuppe": {
    ingredients: [
      { name: "Rindfleisch", amount: 300, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 300, unit: "g", allergens: [] },
      { name: "Paprikapulver edelsüß", amount: 2, unit: "EL", allergens: [] },
      { name: "Tomatenmark", amount: 30, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Essig", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Rindfleisch in Würfel schneiden",
      "Zwiebeln fein würfeln und in Öl goldbraun rösten",
      "Paprikapulver einrühren, sofort mit Essig ablöschen",
      "Fleisch zugeben und anbraten, Tomatenmark einrühren",
      "Mit Rindssuppe aufgießen, Kümmel zugeben",
      "90 Minuten weich schmoren, Kartoffeln zugeben",
      "Weitere 20 Minuten kochen, abschmecken",
    ],
    allergens: ["L"],
  },
  "Serbische Bohnensuppe": {
    ingredients: [
      { name: "Weiße Bohnen (Dose)", amount: 400, unit: "g", allergens: [] },
      { name: "Paprika rot", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Cabanossi", amount: 100, unit: "g", allergens: [] },
      { name: "Paprikapulver edelsüß", amount: 1, unit: "EL", allergens: [] },
      { name: "Tomatenmark", amount: 20, unit: "g", allergens: [] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebel und Knoblauch anbraten, Cabanossi in Scheiben zugeben",
      "Paprikapulver einrühren, Tomatenmark zugeben",
      "Paprika würfeln und zugeben, mit Brühe aufgießen",
      "Bohnen zugeben, 20 Minuten köcheln",
      "Mit Salz und Pfeffer abschmecken",
    ],
    allergens: ["L"],
  },
  "Kichererbsensuppe": {
    ingredients: [
      { name: "Kichererbsen (Dose)", amount: 400, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Kreuzkümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Olivenöl", amount: 2, unit: "EL", allergens: [] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Zitronensaft", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebel und Knoblauch in Olivenöl anschwitzen",
      "Kreuzkümmel einrühren, Karotten zugeben",
      "Kichererbsen und Brühe zugeben, 20 Minuten kochen",
      "Teilweise pürieren, mit Zitronensaft und Salz abschmecken",
    ],
    allergens: ["L"],
  },
  "Ribollita": {
    ingredients: [
      { name: "Weißbrot altbacken", amount: 200, unit: "g", allergens: ["A"] },
      { name: "Schwarzkohl / Grünkohl", amount: 300, unit: "g", allergens: [] },
      { name: "Weiße Bohnen (Dose)", amount: 400, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 60, unit: "g", allergens: ["L"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Tomaten (Dose)", amount: 200, unit: "g", allergens: [] },
      { name: "Olivenöl", amount: 4, unit: "EL", allergens: [] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
    ],
    steps: [
      "Gemüse klein schneiden und in Olivenöl anschwitzen",
      "Tomaten und Brühe zugeben, 20 Minuten kochen",
      "Bohnen und Grünkohl zugeben, weitere 15 Minuten kochen",
      "Brot in Stücke reißen und untermischen",
      "Im Ofen bei 180°C 20 Minuten überbacken",
    ],
    allergens: ["A", "L"],
  },
  "Kartoffelgulaschsuppe": {
    ingredients: [
      { name: "Kartoffeln", amount: 500, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 200, unit: "g", allergens: [] },
      { name: "Paprikapulver edelsüß", amount: 2, unit: "EL", allergens: [] },
      { name: "Tomatenmark", amount: 20, unit: "g", allergens: [] },
      { name: "Debreziner", amount: 2, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Gemüsebrühe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Essig", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebeln in Öl goldbraun rösten",
      "Paprikapulver einrühren, sofort mit Essig ablöschen",
      "Tomatenmark einrühren, Kartoffeln und Knoblauch zugeben",
      "Mit Brühe aufgießen, Kümmel zugeben",
      "25 Minuten kochen, Debreziner in Scheiben zugeben",
      "Weitere 5 Minuten köcheln, abschmecken",
    ],
    allergens: ["L"],
  },
  "Rote-Linsen-Suppe": {
    ingredients: [
      { name: "Rote Linsen", amount: 200, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Ingwer", amount: 10, unit: "g", allergens: [] },
      { name: "Kreuzkümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Kurkuma", amount: 1, unit: "TL", allergens: [] },
      { name: "Kokosmilch", amount: 200, unit: "ml", allergens: [] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Zitronensaft", amount: 1, unit: "EL", allergens: [] },
    ],
    steps: [
      "Linsen waschen, Zwiebel, Knoblauch und Ingwer fein hacken",
      "In Öl anschwitzen, Gewürze einrühren",
      "Karotten, Linsen und Brühe zugeben, 20 Minuten kochen",
      "Pürieren, Kokosmilch einrühren",
      "Mit Zitronensaft und Salz abschmecken",
    ],
    allergens: ["L"],
  },

  // ══════════════════════════════════════════════════
  // INTERNATIONALE & SAISONALE (15)
  // ══════════════════════════════════════════════════
  "Französische Zwiebelsuppe": {
    ingredients: [
      { name: "Zwiebeln", amount: 600, unit: "g", allergens: [] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Weißwein", amount: 150, unit: "ml", allergens: ["O"] },
      { name: "Rindssuppe", amount: 1000, unit: "ml", allergens: ["L"] },
      { name: "Baguette", amount: 4, unit: "Scheiben", allergens: ["A"] },
      { name: "Gruyère gerieben", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebeln halbieren und in feine Streifen schneiden",
      "In Butter bei mittlerer Hitze 30 Minuten karamellisieren",
      "Mit Weißwein ablöschen, einkochen lassen",
      "Rindssuppe und Thymian zugeben, 20 Minuten köcheln",
      "In ofenfeste Schalen füllen, Baguette und Käse darauf",
      "Im Ofen bei 200°C überbacken bis Käse goldbraun",
    ],
    allergens: ["A", "G", "L", "O"],
  },
  "Gazpacho": {
    ingredients: [
      { name: "Tomaten reif", amount: 600, unit: "g", allergens: [] },
      { name: "Gurke", amount: 200, unit: "g", allergens: [] },
      { name: "Paprika rot", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Weißbrot entrindet", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Olivenöl", amount: 4, unit: "EL", allergens: [] },
      { name: "Sherryessig", amount: 2, unit: "EL", allergens: ["O"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Tomaten, Gurke und Paprika grob zerkleinern",
      "Weißbrot in Wasser einweichen",
      "Alles zusammen fein pürieren",
      "Olivenöl und Sherryessig einrühren",
      "Mindestens 2 Stunden kalt stellen",
      "Eiskalt servieren mit Gemüsewürfeln als Topping",
    ],
    allergens: ["A", "O"],
  },
  "Kalte Gurkensuppe": {
    ingredients: [
      { name: "Salatgurken", amount: 600, unit: "g", allergens: [] },
      { name: "Joghurt natur", amount: 300, unit: "ml", allergens: ["G"] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Dill", amount: 1, unit: "Bund", allergens: [] },
      { name: "Olivenöl", amount: 2, unit: "EL", allergens: [] },
      { name: "Zitronensaft", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Gurken schälen, entkernen und grob würfeln",
      "Mit Joghurt und Knoblauch fein pürieren",
      "Dill fein hacken und einrühren",
      "Mit Olivenöl, Zitronensaft und Salz abschmecken",
      "Mindestens 1 Stunde kalt stellen, eiskalt servieren",
    ],
    allergens: ["G"],
  },
  "Thai-Kokossuppe": {
    ingredients: [
      { name: "Kokosmilch", amount: 400, unit: "ml", allergens: [] },
      { name: "Hühnerbrühe", amount: 400, unit: "ml", allergens: [] },
      { name: "Champignons", amount: 150, unit: "g", allergens: [] },
      { name: "Zitronengras", amount: 2, unit: "Stk", allergens: [] },
      { name: "Galgant / Ingwer", amount: 20, unit: "g", allergens: [] },
      { name: "Limettensaft", amount: 2, unit: "EL", allergens: [] },
      { name: "Fischsauce", amount: 2, unit: "EL", allergens: ["D"] },
      { name: "Chilischote", amount: 1, unit: "Stk", allergens: [] },
      { name: "Koriander frisch", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Kokosmilch und Brühe mit Zitronengras und Galgant aufkochen",
      "10 Minuten ziehen lassen",
      "Champignons zugeben, 5 Minuten kochen",
      "Mit Fischsauce, Limettensaft und Chili abschmecken",
      "Zitronengras und Galgant entfernen",
      "Mit frischem Koriander servieren",
    ],
    allergens: ["D"],
  },
  "Hühnersuppe mit Einlage": {
    ingredients: [
      { name: "Suppenhuhn", amount: 1, unit: "Stk", allergens: [] },
      { name: "Karotten", amount: 200, unit: "g", allergens: [] },
      { name: "Sellerie", amount: 80, unit: "g", allergens: ["L"] },
      { name: "Lauch", amount: 80, unit: "g", allergens: [] },
      { name: "Suppennudeln", amount: 80, unit: "g", allergens: ["A", "C"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Suppenhuhn in kaltem Wasser aufsetzen, langsam erhitzen",
      "Schaum abschöpfen, Gemüse und Gewürze zugeben",
      "2 Stunden köcheln lassen",
      "Huhn herausnehmen, Fleisch von den Knochen lösen",
      "Suppe abseihen, Nudeln darin kochen",
      "Fleischstücke zurückgeben, mit Petersilie servieren",
    ],
    allergens: ["A", "C", "L"],
  },
  "Pilzrahmsuppe": {
    ingredients: [
      { name: "Gemischte Pilze", amount: 400, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 20, unit: "g", allergens: ["A"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 600, unit: "ml", allergens: ["L"] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Pilze putzen und in Scheiben schneiden",
      "Zwiebel in Butter anschwitzen, Pilze kräftig anbraten",
      "Mit Mehl bestäuben, mit Brühe ablöschen",
      "15 Minuten köcheln, Schlagobers und Thymian einrühren",
      "Leicht pürieren (cremig aber noch stückig)",
      "Mit Salz und Pfeffer abschmecken",
    ],
    allergens: ["A", "G", "L"],
  },
  "Waldviertler Mohnsuppe": {
    ingredients: [
      { name: "Mohn gemahlen", amount: 80, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Milch", amount: 300, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 500, unit: "ml", allergens: ["L"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Zucker", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffeln in Brühe weich kochen und pürieren",
      "Mohn in trockener Pfanne kurz anrösten",
      "Milch erwärmen, Mohn einrühren",
      "Zum Kartoffelpüree geben, mit Butter verfeinern",
      "Mit Zucker und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Weinsuppe": {
    ingredients: [
      { name: "Weißwein trocken", amount: 500, unit: "ml", allergens: ["O"] },
      { name: "Gemüsebrühe", amount: 300, unit: "ml", allergens: ["L"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Eigelb", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Zucker", amount: 2, unit: "EL", allergens: [] },
      { name: "Zimt", amount: 1, unit: "Prise", allergens: [] },
      { name: "Gewürznelke", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Wein und Brühe mit Zimt und Nelke aufkochen",
      "5 Minuten köcheln, Gewürze entfernen",
      "Eigelb mit Schlagobers und Zucker verquirlen",
      "Langsam in die heiße Suppe einrühren (Legieren)",
      "Nicht mehr kochen lassen! Sofort servieren",
    ],
    allergens: ["C", "G", "L", "O"],
  },
  "Käsesuppe": {
    ingredients: [
      { name: "Bergkäse gerieben", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebel in Butter anschwitzen, Kartoffeln zugeben",
      "Mit Brühe aufgießen, 20 Minuten kochen",
      "Pürieren, Schlagobers einrühren",
      "Käse bei niedriger Hitze einrühren bis geschmolzen",
      "Mit Muskatnuss abschmecken (nicht mehr kochen!)",
    ],
    allergens: ["G", "L"],
  },
  "Topinambur-Suppe": {
    ingredients: [
      { name: "Topinambur", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Topinambur schälen (in Zitronenwasser legen gegen Verfärbung)",
      "Zwiebel in Butter anschwitzen, Topinambur und Kartoffeln zugeben",
      "Mit Brühe aufgießen, 20 Minuten weich kochen",
      "Fein pürieren, Schlagobers einrühren",
      "Mit Muskatnuss und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Pastinaken-Suppe": {
    ingredients: [
      { name: "Pastinaken", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Pastinaken und Kartoffeln schälen und würfeln",
      "Zwiebel in Butter anschwitzen, Gemüse zugeben",
      "Mit Brühe aufgießen, 20 Minuten weich kochen",
      "Fein pürieren, Schlagobers einrühren",
      "Mit Muskatnuss und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Petersilienwurzel-Suppe": {
    ingredients: [
      { name: "Petersilienwurzeln", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 100, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Petersilienwurzeln und Kartoffeln schälen und würfeln",
      "Zwiebel in Butter anschwitzen, Wurzelgemüse zugeben",
      "Mit Brühe aufgießen, 20 Minuten weich kochen",
      "Fein pürieren, Schlagobers einrühren",
      "Mit gehackter Petersilie garnieren und abschmecken",
    ],
    allergens: ["G", "L"],
  },
  "Süßkartoffelsuppe": {
    ingredients: [
      { name: "Süßkartoffeln", amount: 500, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Ingwer", amount: 10, unit: "g", allergens: [] },
      { name: "Kokosmilch", amount: 200, unit: "ml", allergens: [] },
      { name: "Gemüsebrühe", amount: 600, unit: "ml", allergens: ["L"] },
      { name: "Limettensaft", amount: 1, unit: "EL", allergens: [] },
      { name: "Olivenöl", amount: 2, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Süßkartoffeln schälen und würfeln",
      "Zwiebel und Ingwer in Öl anschwitzen",
      "Süßkartoffeln zugeben, mit Brühe aufgießen",
      "20 Minuten weich kochen, pürieren",
      "Kokosmilch einrühren, mit Limettensaft und Salz abschmecken",
    ],
    allergens: ["L"],
  },
  "Rote-Rüben-Suppe (Borschtsch)": {
    ingredients: [
      { name: "Rote Rüben roh", amount: 400, unit: "g", allergens: [] },
      { name: "Rindfleisch", amount: 200, unit: "g", allergens: [] },
      { name: "Weißkraut", amount: 150, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 150, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Sauerrahm", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Essig", amount: 2, unit: "EL", allergens: [] },
      { name: "Rindssuppe", amount: 1200, unit: "ml", allergens: ["L"] },
      { name: "Dill", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Rindfleisch in Brühe weich kochen, herausnehmen und würfeln",
      "Rote Rüben und Gemüse schälen und in feine Streifen schneiden",
      "In der Brühe mit Kraut und Kartoffeln 20 Minuten kochen",
      "Rote Rüben und Fleisch zugeben, mit Essig abschmecken",
      "Mit Sauerrahm und Dill servieren",
    ],
    allergens: ["G", "L"],
  },
  "Fisolen-Suppe": {
    ingredients: [
      { name: "Fisolen (grüne Bohnen)", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Speck", amount: 50, unit: "g", allergens: [] },
      { name: "Essig", amount: 2, unit: "EL", allergens: [] },
      { name: "Gemüsebrühe", amount: 800, unit: "ml", allergens: ["L"] },
      { name: "Bohnenkraut", amount: 1, unit: "TL", allergens: [] },
      { name: "Sauerrahm", amount: 50, unit: "ml", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Fisolen putzen und in 3 cm Stücke schneiden",
      "Speck und Zwiebel anbraten, Kartoffeln zugeben",
      "Mit Brühe aufgießen, Fisolen und Bohnenkraut zugeben",
      "20 Minuten weich kochen",
      "Mit Essig, Sauerrahm und Salz abschmecken",
    ],
    allergens: ["G", "L"],
  },
};
