/**
 * Vegetarian/Vegan recipe completion data — 70 recipes (MainVegan)
 */
import type { RecipeCompletionMap } from "../complete-recipes";

export const VEGETARIAN_DATA: RecipeCompletionMap = {
  // ══════════════════════════════════════════════════
  // TEIGWAREN (15)
  // ══════════════════════════════════════════════════
  "Käsespätzle": {
    ingredients: [
      { name: "Mehl griffig", amount: 300, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 4, unit: "Stk", allergens: ["C"] },
      { name: "Wasser", amount: 150, unit: "ml", allergens: [] },
      { name: "Bergkäse gerieben", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Zwiebeln", amount: 3, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Spätzleteig aus Mehl, Eiern, Wasser und Salz rühren, 15 Min rasten",
      "Durch Spätzlepresse in kochendes Salzwasser drücken",
      "Aufsteigen lassen und abschöpfen",
      "Schichtweise mit Käse in eine Auflaufform geben",
      "Zwiebeln in Butter goldbraun rösten",
      "Röstzwiebeln über die Käsespätzle geben, im Ofen kurz überbacken",
    ],
    allergens: ["A", "C", "G"],
  },
  "Krautfleckerl": {
    ingredients: [
      { name: "Fleckerl (Nudeln)", amount: 300, unit: "g", allergens: ["A", "C"] },
      { name: "Weißkraut", amount: 500, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Schmalz / Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Zucker", amount: 1, unit: "EL", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Kraut fein hobeln und salzen, 15 Min ziehen lassen, ausdrücken",
      "Zwiebel in Schmalz anschwitzen, Zucker zugeben (karamellisieren)",
      "Kraut zugeben und 20-30 Minuten dünsten bis weich und leicht gebräunt",
      "Fleckerl bissfest kochen und unter das Kraut mischen",
      "Mit Kümmel würzen und abschmecken",
    ],
    allergens: ["A", "C", "G"],
  },
  "Schinkenfleckerl": {
    ingredients: [
      { name: "Fleckerl (Nudeln)", amount: 300, unit: "g", allergens: ["A", "C"] },
      { name: "Kochschinken", amount: 200, unit: "g", allergens: [] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Fleckerl bissfest kochen",
      "Schinken in Streifen schneiden",
      "Eier mit Schlagobers und Muskatnuss verquirlen",
      "Fleckerl, Schinken und Eier-Mischung in gebutterte Auflaufform",
      "Bei 180°C 25-30 Minuten goldbraun backen",
      "Mit Petersilie bestreuen und servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Spinatspätzle mit Käsesauce": {
    ingredients: [
      { name: "Mehl griffig", amount: 300, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Blattspinat (TK)", amount: 150, unit: "g", allergens: [] },
      { name: "Bergkäse", amount: 150, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Spinat auftauen, ausdrücken und fein hacken",
      "Spätzleteig mit Spinat grün färben",
      "Durch Spätzlepresse in Salzwasser garen",
      "Für die Sauce: Schlagobers aufkochen, Käse einschmelzen",
      "Spätzle mit Käsesauce überziehen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Pasta Arrabiata": {
    ingredients: [
      { name: "Penne", amount: 400, unit: "g", allergens: ["A"] },
      { name: "Tomaten (Dose)", amount: 400, unit: "g", allergens: [] },
      { name: "Knoblauch", amount: 3, unit: "Stk", allergens: [] },
      { name: "Chilischote", amount: 2, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 4, unit: "EL", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Knoblauch und Chili in Olivenöl bei niedriger Hitze anbraten",
      "Tomaten zugeben und 15 Minuten einkochen",
      "Penne al dente kochen",
      "Pasta mit der Sauce schwenken",
      "Mit Petersilie servieren",
    ],
    allergens: ["A"],
  },
  "Pasta Pomodoro": {
    ingredients: [
      { name: "Spaghetti", amount: 400, unit: "g", allergens: ["A"] },
      { name: "Tomaten reif", amount: 500, unit: "g", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 4, unit: "EL", allergens: [] },
      { name: "Basilikum", amount: 1, unit: "Bund", allergens: [] },
      { name: "Parmesan", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Tomaten häuten und würfeln",
      "Knoblauch in Olivenöl sanft anbraten",
      "Tomaten zugeben, 15 Min köcheln",
      "Spaghetti al dente kochen",
      "Mit Sauce, Basilikum und Parmesan servieren",
    ],
    allergens: ["A", "G"],
  },
  "Penne al Forno": {
    ingredients: [
      { name: "Penne", amount: 400, unit: "g", allergens: ["A"] },
      { name: "Tomatensauce", amount: 400, unit: "ml", allergens: [] },
      { name: "Mozzarella", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Parmesan", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Basilikum", amount: 4, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Penne bissfest kochen",
      "Mit Tomatensauce mischen",
      "In Auflaufform füllen, Mozzarella darüber verteilen",
      "Parmesan darüber reiben",
      "Bei 200°C 20 Minuten überbacken",
      "Mit Basilikum servieren",
    ],
    allergens: ["A", "G"],
  },
  "Lasagne vegetarisch": {
    ingredients: [
      { name: "Lasagneblätter", amount: 250, unit: "g", allergens: ["A", "C"] },
      { name: "Zucchini", amount: 200, unit: "g", allergens: [] },
      { name: "Aubergine", amount: 200, unit: "g", allergens: [] },
      { name: "Tomatensauce", amount: 500, unit: "ml", allergens: [] },
      { name: "Béchamelsauce", amount: 400, unit: "ml", allergens: ["A", "G"] },
      { name: "Mozzarella", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Parmesan", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Gemüse in Scheiben schneiden und in Olivenöl anbraten",
      "Auflaufform einfetten, schichtweise: Sauce, Lasagneblätter, Gemüse, Béchamel",
      "3-4 Schichten aufbauen, mit Béchamel und Käse abschließen",
      "Bei 180°C 35-40 Minuten backen",
      "10 Minuten ruhen lassen vor dem Anschneiden",
    ],
    allergens: ["A", "C", "G"],
  },
  "Nudeln mit Pesto": {
    ingredients: [
      { name: "Spaghetti", amount: 400, unit: "g", allergens: ["A"] },
      { name: "Basilikum frisch", amount: 50, unit: "g", allergens: [] },
      { name: "Pinienkerne", amount: 30, unit: "g", allergens: ["H"] },
      { name: "Parmesan", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 100, unit: "ml", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Pinienkerne ohne Fett goldbraun rösten",
      "Basilikum, Pinienkerne, Knoblauch und Parmesan im Mörser oder Mixer zerkleinern",
      "Olivenöl langsam einarbeiten, salzen",
      "Spaghetti al dente kochen, etwas Kochwasser aufheben",
      "Pesto mit Pasta und etwas Kochwasser vermengen",
    ],
    allergens: ["A", "G", "H"],
  },
  "Rigatoni mit Gemüseragout": {
    ingredients: [
      { name: "Rigatoni", amount: 400, unit: "g", allergens: ["A"] },
      { name: "Zucchini", amount: 150, unit: "g", allergens: [] },
      { name: "Paprika", amount: 1, unit: "Stk", allergens: [] },
      { name: "Aubergine", amount: 150, unit: "g", allergens: [] },
      { name: "Tomaten (Dose)", amount: 400, unit: "g", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 3, unit: "EL", allergens: [] },
      { name: "Basilikum", amount: 4, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Gemüse würfeln und in Olivenöl anbraten",
      "Knoblauch und Tomaten zugeben, 15 Minuten köcheln",
      "Rigatoni al dente kochen",
      "Pasta mit Ragout mischen, mit Basilikum servieren",
    ],
    allergens: ["A"],
  },
  "Tortellini in Sahnesauce": {
    ingredients: [
      { name: "Tortellini (Käsefüllung)", amount: 500, unit: "g", allergens: ["A", "C", "G"] },
      { name: "Schlagobers", amount: 300, unit: "ml", allergens: ["G"] },
      { name: "Parmesan", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Tortellini nach Packungsanweisung kochen",
      "Schlagobers aufkochen und leicht einreduzieren",
      "Parmesan einrühren, mit Muskatnuss würzen",
      "Tortellini mit Sahnesauce überziehen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Spaghetti Aglio e Olio": {
    ingredients: [
      { name: "Spaghetti", amount: 400, unit: "g", allergens: ["A"] },
      { name: "Knoblauch", amount: 6, unit: "Stk", allergens: [] },
      { name: "Chilischote", amount: 2, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 100, unit: "ml", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Spaghetti al dente kochen, Kochwasser aufheben",
      "Knoblauch in Scheiben und Chili in Olivenöl bei niedriger Hitze goldbraun braten",
      "Sofort Pasta und 2-3 EL Kochwasser zugeben",
      "Schwenken bis eine seidige Emulsion entsteht",
      "Mit Petersilie servieren",
    ],
    allergens: ["A"],
  },
  "Mac and Cheese": {
    ingredients: [
      { name: "Makkaroni", amount: 400, unit: "g", allergens: ["A"] },
      { name: "Cheddar gerieben", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Gouda gerieben", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Mehl", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Milch", amount: 500, unit: "ml", allergens: ["G"] },
      { name: "Semmelbrösel", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Makkaroni bissfest kochen",
      "Béchamel: Butter, Mehl, Milch zu glatter Sauce kochen",
      "Käse einschmelzen, mit Muskatnuss würzen",
      "Nudeln untermischen, in Auflaufform füllen",
      "Semmelbrösel darüber, bei 200°C 15 Min überbacken",
    ],
    allergens: ["A", "G"],
  },
  "Nudelauflauf mit Gemüse": {
    ingredients: [
      { name: "Spiralnudeln", amount: 300, unit: "g", allergens: ["A"] },
      { name: "Zucchini", amount: 150, unit: "g", allergens: [] },
      { name: "Paprika", amount: 1, unit: "Stk", allergens: [] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Käse gerieben", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Nudeln bissfest kochen, Gemüse würfeln und anbraten",
      "Eier mit Schlagobers verquirlen",
      "Nudeln und Gemüse in Auflaufform schichten",
      "Eiermischung darüber gießen, Käse bestreuen",
      "Bei 180°C 25 Minuten goldbraun backen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Pasta mit Kürbissauce": {
    ingredients: [
      { name: "Tagliatelle", amount: 400, unit: "g", allergens: ["A"] },
      { name: "Hokkaido-Kürbis", amount: 400, unit: "g", allergens: [] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Salbei", amount: 8, unit: "Stk", allergens: [] },
      { name: "Parmesan", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kürbis entkernen und in Würfel schneiden",
      "In Butter anbraten, mit wenig Wasser weich dünsten",
      "Pürieren, Schlagobers einrühren",
      "Salbeiblätter in Butter knusprig braten",
      "Tagliatelle kochen, mit Kürbissauce, Salbei und Parmesan servieren",
    ],
    allergens: ["A", "G"],
  },

  // ══════════════════════════════════════════════════
  // STRUDEL & QUICHE (10)
  // ══════════════════════════════════════════════════
  "Gemüsestrudel": {
    ingredients: [
      { name: "Strudelteig", amount: 250, unit: "g", allergens: ["A"] },
      { name: "Zucchini", amount: 150, unit: "g", allergens: [] },
      { name: "Paprika", amount: 1, unit: "Stk", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Lauch", amount: 100, unit: "g", allergens: [] },
      { name: "Schafkäse", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 40, unit: "g", allergens: ["A"] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
    ],
    steps: [
      "Gemüse klein schneiden und in Butter dünsten",
      "Abkühlen lassen, Schafkäse und Eier untermischen",
      "Strudelteig ausziehen, mit flüssiger Butter bestreichen",
      "Semmelbrösel darüber streuen, Füllung verteilen",
      "Einrollen, Enden einschlagen",
      "Bei 180°C 30-35 Minuten goldbraun backen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Krautstrudel": {
    ingredients: [
      { name: "Strudelteig", amount: 250, unit: "g", allergens: ["A"] },
      { name: "Weißkraut", amount: 500, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Zucker", amount: 1, unit: "EL", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Semmelbrösel", amount: 40, unit: "g", allergens: ["A"] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Kraut fein hobeln, salzen und ausdrücken",
      "Zwiebel in Butter anschwitzen, Zucker karamellisieren",
      "Kraut zugeben, 20 Minuten dünsten, mit Kümmel würzen",
      "Strudelteig buttern, Brösel darauf, Füllung verteilen",
      "Einrollen, bei 180°C 30 Minuten backen",
    ],
    allergens: ["A", "G"],
  },
  "Spinatstrudel": {
    ingredients: [
      { name: "Strudelteig", amount: 250, unit: "g", allergens: ["A"] },
      { name: "Blattspinat", amount: 500, unit: "g", allergens: [] },
      { name: "Schafkäse", amount: 150, unit: "g", allergens: ["G"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Spinat waschen und in Butter zusammenfallen lassen",
      "Zwiebel und Knoblauch anschwitzen, unter den Spinat mischen",
      "Schafkäse zerbröseln und unterheben",
      "Strudelteig buttern, Füllung verteilen, einrollen",
      "Bei 180°C 30 Minuten goldbraun backen",
    ],
    allergens: ["A", "G"],
  },
  "Kürbis-Feta-Strudel": {
    ingredients: [
      { name: "Blätterteig", amount: 250, unit: "g", allergens: ["A", "G"] },
      { name: "Hokkaido-Kürbis", amount: 400, unit: "g", allergens: [] },
      { name: "Feta", amount: 150, unit: "g", allergens: ["G"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Kürbiskerne", amount: 30, unit: "g", allergens: [] },
      { name: "Eigelb", amount: 1, unit: "Stk", allergens: ["C"] },
    ],
    steps: [
      "Kürbis entkernen, würfeln und im Ofen rösten (200°C, 20 Min)",
      "Mit Feta, Zwiebel und Thymian mischen",
      "Auf Blätterteig verteilen, einrollen",
      "Mit Eigelb bestreichen, Kürbiskerne darauf",
      "Bei 180°C 25-30 Minuten goldbraun backen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Quiche Lorraine": {
    ingredients: [
      { name: "Mürbteig", amount: 250, unit: "g", allergens: ["A", "G"] },
      { name: "Speck", amount: 150, unit: "g", allergens: [] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Gruyère", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Mürbteig in Tarteform auslegen, blind vorbacken (180°C, 10 Min)",
      "Speck in Streifen braten und auf den Teig verteilen",
      "Eier, Schlagobers und Muskatnuss verquirlen, Käse untermischen",
      "Guss über den Speck gießen",
      "Bei 180°C 30-35 Minuten goldbraun backen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Gemüsequiche": {
    ingredients: [
      { name: "Mürbteig", amount: 250, unit: "g", allergens: ["A", "G"] },
      { name: "Brokkoli", amount: 200, unit: "g", allergens: [] },
      { name: "Paprika", amount: 1, unit: "Stk", allergens: [] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Käse gerieben", amount: 80, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Teig in Form auslegen und blind vorbacken",
      "Gemüse blanchieren und auf dem Teig verteilen",
      "Eier-Sahne-Guss darüber gießen, Käse bestreuen",
      "Bei 180°C 30 Minuten backen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Zwiebelkuchen": {
    ingredients: [
      { name: "Hefeteig", amount: 300, unit: "g", allergens: ["A"] },
      { name: "Zwiebeln", amount: 600, unit: "g", allergens: [] },
      { name: "Speck", amount: 100, unit: "g", allergens: [] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Sauerrahm", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Hefeteig in Backblech auslegen",
      "Zwiebeln in Ringe schneiden und glasig dünsten",
      "Speck anbraten, mit Zwiebeln, Eiern und Sauerrahm mischen",
      "Auf den Teig verteilen, mit Kümmel bestreuen",
      "Bei 180°C 35 Minuten backen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Lauchquiche": {
    ingredients: [
      { name: "Mürbteig", amount: 250, unit: "g", allergens: ["A", "G"] },
      { name: "Lauch", amount: 400, unit: "g", allergens: [] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Käse gerieben", amount: 80, unit: "g", allergens: ["G"] },
      { name: "Butter", amount: 20, unit: "g", allergens: ["G"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Teig in Form auslegen, blind vorbacken",
      "Lauch in Ringe schneiden und in Butter dünsten",
      "Eier-Sahne-Guss darüber gießen, Käse bestreuen",
      "Bei 180°C 30 Minuten goldbraun backen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Tomaten-Ziegenkäse-Tarte": {
    ingredients: [
      { name: "Blätterteig", amount: 250, unit: "g", allergens: ["A", "G"] },
      { name: "Tomaten", amount: 400, unit: "g", allergens: [] },
      { name: "Ziegenkäse", amount: 150, unit: "g", allergens: ["G"] },
      { name: "Senf", amount: 1, unit: "EL", allergens: ["M"] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 2, unit: "EL", allergens: [] },
    ],
    steps: [
      "Blätterteig ausrollen und in Tarteform legen",
      "Teig dünn mit Senf bestreichen",
      "Tomaten in Scheiben schneiden und fächerartig auflegen",
      "Ziegenkäse zerbröseln und darüber verteilen",
      "Mit Thymian und Olivenöl beträufeln",
      "Bei 200°C 25 Minuten backen",
    ],
    allergens: ["A", "G", "M"],
  },
  "Flammkuchen vegetarisch": {
    ingredients: [
      { name: "Pizzateig / Flammkuchenteig", amount: 300, unit: "g", allergens: ["A"] },
      { name: "Crème fraîche", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Zwiebeln", amount: 2, unit: "Stk", allergens: [] },
      { name: "Zucchini", amount: 150, unit: "g", allergens: [] },
      { name: "Schafkäse", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Thymian", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Teig hauchdünn ausrollen",
      "Crème fraîche dünn verstreichen",
      "Zwiebeln in Ringe, Zucchini in dünne Scheiben schneiden",
      "Gemüse und Schafkäse darauf verteilen",
      "Bei 250°C 10-12 Minuten knusprig backen",
    ],
    allergens: ["A", "G"],
  },

  // ══════════════════════════════════════════════════
  // KNÖDEL & NOCKERL (8)
  // ══════════════════════════════════════════════════
  "Spinatknödel": {
    ingredients: [
      { name: "Semmeln altbacken", amount: 4, unit: "Stk", allergens: ["A"] },
      { name: "Blattspinat", amount: 300, unit: "g", allergens: [] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Milch", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Parmesan", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Semmeln würfeln und in lauwarmer Milch einweichen",
      "Spinat blanchieren, ausdrücken und fein hacken",
      "Zwiebel in Butter anschwitzen",
      "Alle Zutaten vermengen, 15 Minuten rasten lassen",
      "Knödel formen und in Salzwasser 15 Minuten ziehen lassen",
      "Mit brauner Butter und Parmesan servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Kaspressknödel": {
    ingredients: [
      { name: "Semmeln altbacken", amount: 3, unit: "Stk", allergens: ["A"] },
      { name: "Bergkäse gerieben", amount: 150, unit: "g", allergens: ["G"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Milch", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
    ],
    steps: [
      "Semmeln würfeln und in Milch einweichen",
      "Zwiebel in Butter anschwitzen",
      "Semmelwürfel, Käse, Eier, Zwiebel und Petersilie vermengen",
      "Zu flachen Laibchen formen",
      "In Butter beidseitig goldbraun braten",
      "In Rindssuppe oder mit Salat servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Topfenknödel": {
    ingredients: [
      { name: "Topfen 20%", amount: 500, unit: "g", allergens: ["G"] },
      { name: "Butter", amount: 60, unit: "g", allergens: ["G"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Grieß", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Semmelbrösel", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Zucker", amount: 40, unit: "g", allergens: [] },
      { name: "Vanillezucker", amount: 1, unit: "TL", allergens: [] },
      { name: "Butterbrösel zum Wälzen", amount: 80, unit: "g", allergens: ["A", "G"] },
      { name: "Staubzucker", amount: 2, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Butter schaumig rühren, Eier und Zucker einrühren",
      "Topfen, Grieß und Semmelbrösel unterheben",
      "30 Minuten im Kühlschrank rasten lassen",
      "Mit nassen Händen Knödel formen",
      "In leicht siedendem Wasser 12-15 Minuten ziehen lassen",
      "In Butterbröseln wälzen und mit Staubzucker bestreuen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Marillenknödel": {
    ingredients: [
      { name: "Kartoffeln mehlig gekocht", amount: 500, unit: "g", allergens: [] },
      { name: "Mehl glatt", amount: 100, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Marillen (Aprikosen)", amount: 8, unit: "Stk", allergens: [] },
      { name: "Würfelzucker", amount: 8, unit: "Stk", allergens: [] },
      { name: "Butterbrösel", amount: 100, unit: "g", allergens: ["A", "G"] },
      { name: "Staubzucker", amount: 2, unit: "EL", allergens: [] },
      { name: "Zimt", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffeln durch die Presse drücken, mit Mehl und Ei zu Teig verarbeiten",
      "Marillen entsteinen, Zuckerstück in die Mitte stecken",
      "Teigstücke flach drücken, Marillen einwickeln",
      "In leicht siedendem Wasser 12-15 Minuten kochen",
      "In Butterbröseln wälzen",
      "Mit Staubzucker und Zimt servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Zwetschgenknödel": {
    ingredients: [
      { name: "Kartoffeln mehlig gekocht", amount: 500, unit: "g", allergens: [] },
      { name: "Mehl glatt", amount: 100, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Zwetschgen entsteint", amount: 12, unit: "Stk", allergens: [] },
      { name: "Würfelzucker", amount: 12, unit: "Stk", allergens: [] },
      { name: "Butterbrösel", amount: 100, unit: "g", allergens: ["A", "G"] },
      { name: "Staubzucker", amount: 2, unit: "EL", allergens: [] },
      { name: "Zimt", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffelteig wie bei Marillenknödel herstellen",
      "Zwetschgen entsteinen, Zucker hineinstecken",
      "In Teig einwickeln, in Salzwasser 12-15 Minuten kochen",
      "In Butterbröseln wälzen",
      "Mit Staubzucker und Zimt servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Mohnnudeln": {
    ingredients: [
      { name: "Kartoffeln mehlig gekocht", amount: 500, unit: "g", allergens: [] },
      { name: "Mehl glatt", amount: 100, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Mohn gemahlen", amount: 100, unit: "g", allergens: [] },
      { name: "Butter", amount: 60, unit: "g", allergens: ["G"] },
      { name: "Staubzucker", amount: 50, unit: "g", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffelteig herstellen: Kartoffeln pressen, mit Mehl und Ei kneten",
      "Zu Rollen formen und in 3 cm Stücke schneiden (Schupfnudel-Form)",
      "In Salzwasser kochen bis sie aufschwimmen",
      "Butter schmelzen, Mohn und Zucker einrühren",
      "Nudeln in der Mohnbutter schwenken",
      "Mit Staubzucker bestreut servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Germknödel": {
    ingredients: [
      { name: "Mehl glatt", amount: 500, unit: "g", allergens: ["A"] },
      { name: "Milch lauwarm", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Germ (Hefe)", amount: 20, unit: "g", allergens: [] },
      { name: "Butter", amount: 60, unit: "g", allergens: ["G"] },
      { name: "Zucker", amount: 50, unit: "g", allergens: [] },
      { name: "Eigelb", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Powidl (Zwetschgenmus)", amount: 150, unit: "g", allergens: [] },
      { name: "Mohnbutter", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Vanillesauce", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Germteig: Milch, Germ, Mehl, Butter, Zucker, Eigelb verkneten",
      "45 Minuten gehen lassen",
      "Teig portionieren, Powidl einfüllen, gut verschließen",
      "Nochmals 20 Minuten gehen lassen",
      "Im Dampf 15 Minuten garen (oder in Salzwasser)",
      "Mit Mohnbutter und Vanillesauce servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Serviettenknödel mit Schwammerlsauce": {
    ingredients: [
      { name: "Semmeln altbacken", amount: 5, unit: "Stk", allergens: ["A"] },
      { name: "Milch", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Gemischte Pilze", amount: 300, unit: "g", allergens: [] },
      { name: "Schlagobers", amount: 150, unit: "ml", allergens: ["G"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Semmeln würfeln, mit warmer Milch übergießen",
      "Eier, Butter und Petersilie untermischen",
      "In Frischhaltefolie zu einer Rolle formen",
      "In Salzwasser 25 Minuten sieden lassen",
      "Pilze mit Zwiebel anbraten, Schlagobers zugeben",
      "Knödel in Scheiben schneiden, mit Schwammerlsauce servieren",
    ],
    allergens: ["A", "C", "G"],
  },

  // ══════════════════════════════════════════════════
  // AUFLÄUFE & GRATINS (8)
  // ══════════════════════════════════════════════════
  "Gemüseauflauf": {
    ingredients: [
      { name: "Zucchini", amount: 200, unit: "g", allergens: [] },
      { name: "Paprika", amount: 1, unit: "Stk", allergens: [] },
      { name: "Karotten", amount: 150, unit: "g", allergens: [] },
      { name: "Brokkoli", amount: 150, unit: "g", allergens: [] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Käse gerieben", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Gemüse waschen, schneiden und kurz blanchieren",
      "In gefettete Auflaufform schichten",
      "Eier mit Schlagobers verquirlen, über das Gemüse gießen",
      "Käse darüber streuen",
      "Bei 180°C 30 Minuten goldbraun backen",
    ],
    allergens: ["C", "G"],
  },
  "Kartoffelgratin": {
    ingredients: [
      { name: "Kartoffeln festkochend", amount: 800, unit: "g", allergens: [] },
      { name: "Schlagobers", amount: 300, unit: "ml", allergens: ["G"] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Salz", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Kartoffeln schälen und in dünne Scheiben schneiden",
      "Form mit Knoblauch ausreiben und buttern",
      "Kartoffeln schuppenartig einschichten",
      "Schlagobers mit Salz und Muskatnuss würzen, darüber gießen",
      "Bei 180°C 50-60 Minuten goldbraun backen",
    ],
    allergens: ["G"],
  },
  "Moussaka vegetarisch": {
    ingredients: [
      { name: "Auberginen", amount: 3, unit: "Stk", allergens: [] },
      { name: "Kartoffeln", amount: 300, unit: "g", allergens: [] },
      { name: "Linsen (braun)", amount: 200, unit: "g", allergens: [] },
      { name: "Tomatensauce", amount: 400, unit: "ml", allergens: [] },
      { name: "Béchamelsauce", amount: 300, unit: "ml", allergens: ["A", "G"] },
      { name: "Käse gerieben", amount: 80, unit: "g", allergens: ["G"] },
      { name: "Olivenöl", amount: 4, unit: "EL", allergens: [] },
    ],
    steps: [
      "Auberginen in Scheiben schneiden, salzen und 20 Min entwässern",
      "In Olivenöl goldbraun braten",
      "Linsen und Kartoffeln vorkochen",
      "Schichtweise in Auflaufform: Auberginen, Linsen-Tomaten, Kartoffeln",
      "Béchamel und Käse obenauf",
      "Bei 180°C 40 Minuten backen",
    ],
    allergens: ["A", "G"],
  },
  "Zucchini-Auflauf": {
    ingredients: [
      { name: "Zucchini", amount: 600, unit: "g", allergens: [] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Sauerrahm", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Käse gerieben", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Semmelbrösel", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zucchini in Scheiben schneiden",
      "Eier mit Sauerrahm und Knoblauch verquirlen",
      "Zucchini in die Form schichten, Guss darüber gießen",
      "Käse und Semmelbrösel bestreuen",
      "Bei 180°C 30 Minuten backen",
    ],
    allergens: ["A", "C", "G"],
  },
  "Broccoli-Gratin": {
    ingredients: [
      { name: "Brokkoli", amount: 600, unit: "g", allergens: [] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Käse gerieben", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Semmelbrösel", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Butter", amount: 20, unit: "g", allergens: ["G"] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Brokkoli in Röschen teilen und bissfest blanchieren",
      "In gebutterte Auflaufform geben",
      "Schlagobers mit Muskatnuss über den Brokkoli gießen",
      "Käse und Semmelbrösel darüber streuen",
      "Bei 200°C 20 Minuten goldbraun überbacken",
    ],
    allergens: ["A", "G"],
  },
  "Polenta mit Schwammerl": {
    ingredients: [
      { name: "Maisgrieß (Polenta)", amount: 200, unit: "g", allergens: [] },
      { name: "Gemischte Pilze", amount: 400, unit: "g", allergens: [] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Parmesan", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Polenta in Salzwasser 20 Min rühren, Butter und Parmesan einrühren",
      "Pilze putzen und in Butter mit Zwiebel und Knoblauch anbraten",
      "Schlagobers zugeben, mit Thymian würzen",
      "Polenta auf Teller, Schwammerlsauce darüber",
    ],
    allergens: ["G"],
  },
  "Polenta-Gemüse-Auflauf": {
    ingredients: [
      { name: "Maisgrieß (Polenta)", amount: 200, unit: "g", allergens: [] },
      { name: "Zucchini", amount: 200, unit: "g", allergens: [] },
      { name: "Paprika", amount: 1, unit: "Stk", allergens: [] },
      { name: "Tomatensauce", amount: 300, unit: "ml", allergens: [] },
      { name: "Mozzarella", amount: 150, unit: "g", allergens: ["G"] },
      { name: "Parmesan", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Olivenöl", amount: 2, unit: "EL", allergens: [] },
    ],
    steps: [
      "Polenta kochen und in eine gefettete Form streichen, abkühlen",
      "Gemüse in Olivenöl anbraten",
      "Tomatensauce über die Polenta gießen, Gemüse darauf verteilen",
      "Mozzarella und Parmesan darüber streuen",
      "Bei 200°C 20 Minuten überbacken",
    ],
    allergens: ["G"],
  },
  "Kürbis-Kartoffel-Gratin": {
    ingredients: [
      { name: "Hokkaido-Kürbis", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 400, unit: "g", allergens: [] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Käse gerieben", amount: 80, unit: "g", allergens: ["G"] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Salbei", amount: 4, unit: "Stk", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kürbis und Kartoffeln in dünne Scheiben schneiden",
      "Abwechselnd in die Form schichten",
      "Schlagobers mit Knoblauch würzen und darüber gießen",
      "Käse und Salbeiblätter obenauf",
      "Bei 180°C 45 Minuten backen",
    ],
    allergens: ["G"],
  },

  // ══════════════════════════════════════════════════
  // LAIBCHEN & BRATLINGE (10)
  // ══════════════════════════════════════════════════
  "Gemüselaibchen": {
    ingredients: [
      { name: "Karotten", amount: 200, unit: "g", allergens: [] },
      { name: "Zucchini", amount: 200, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 60, unit: "g", allergens: ["A"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Öl", amount: 4, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffeln kochen und stampfen, Gemüse fein raspeln",
      "Alles mit Eiern und Semmelbröseln vermengen",
      "Laibchen formen und in Öl goldbraun braten",
      "Mit Kräuterdip und Salat servieren",
    ],
    allergens: ["A", "C"],
  },
  "Erdäpfellaibchen": {
    ingredients: [
      { name: "Kartoffeln mehlig gekocht", amount: 600, unit: "g", allergens: [] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Mehl", amount: 40, unit: "g", allergens: ["A"] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Muskatnuss", amount: 1, unit: "Prise", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffeln pressen, mit Ei, Mehl und Gewürzen vermengen",
      "Flache Laibchen formen",
      "In Butter beidseitig goldbraun braten",
      "Mit Salat oder als Beilage servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Linsenlaibchen": {
    ingredients: [
      { name: "Linsen (braun, gekocht)", amount: 300, unit: "g", allergens: [] },
      { name: "Haferflocken", amount: 60, unit: "g", allergens: ["A"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Kreuzkümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Öl", amount: 4, unit: "EL", allergens: [] },
    ],
    steps: [
      "Linsen grob zerdrücken, nicht pürieren",
      "Zwiebel und Knoblauch anbraten, mit Linsen mischen",
      "Haferflocken und Ei untermischen, 15 Min rasten",
      "Laibchen formen und in Öl braten",
      "Mit Joghurt-Minz-Dip servieren",
    ],
    allergens: ["A", "C"],
  },
  "Kichererbsen-Bratlinge / Falafel": {
    ingredients: [
      { name: "Kichererbsen (Dose)", amount: 500, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Koriander", amount: 1, unit: "TL", allergens: [] },
      { name: "Kreuzkümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Mehl", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Öl zum Frittieren", amount: 300, unit: "ml", allergens: [] },
    ],
    steps: [
      "Kichererbsen, Zwiebel, Knoblauch und Kräuter im Mixer zerkleinern",
      "Gewürze und Mehl untermischen",
      "30 Minuten kalt stellen",
      "Kleine Bällchen formen",
      "Bei 170°C goldbraun frittieren (oder in Pfanne braten)",
      "Mit Hummus und Fladenbrot servieren",
    ],
    allergens: ["A"],
  },
  "Rote-Rüben-Laibchen": {
    ingredients: [
      { name: "Rote Rüben gekocht", amount: 300, unit: "g", allergens: [] },
      { name: "Kartoffeln gekocht", amount: 200, unit: "g", allergens: [] },
      { name: "Haferflocken", amount: 60, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Kren", amount: 1, unit: "EL", allergens: [] },
      { name: "Öl", amount: 4, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Rote Rüben und Kartoffeln fein raspeln",
      "Mit Haferflocken, Ei und Kren vermengen",
      "Laibchen formen und in Öl goldbraun braten",
      "Mit Sauerrahm und Salat servieren",
    ],
    allergens: ["A", "C"],
  },
  "Hirslaibchen": {
    ingredients: [
      { name: "Hirse gekocht", amount: 300, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 40, unit: "g", allergens: ["A"] },
      { name: "Petersilie", amount: 1, unit: "EL", allergens: [] },
      { name: "Öl", amount: 4, unit: "EL", allergens: [] },
    ],
    steps: [
      "Karotten fein raspeln",
      "Hirse mit Karotten, Ei und Semmelbröseln vermengen",
      "Laibchen formen und in Öl goldbraun braten",
    ],
    allergens: ["A", "C"],
  },
  "Zucchini-Puffer": {
    ingredients: [
      { name: "Zucchini", amount: 500, unit: "g", allergens: [] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Mehl", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Dill", amount: 1, unit: "EL", allergens: [] },
      { name: "Öl", amount: 4, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zucchini grob raspeln, salzen und 10 Min entwässern, ausdrücken",
      "Mit Eiern, Mehl, Knoblauch und Dill vermengen",
      "Löffelweise in heißem Öl goldbraun braten",
      "Mit Kräuterrahm servieren",
    ],
    allergens: ["A", "C"],
  },
  "Karotten-Ingwer-Bratlinge": {
    ingredients: [
      { name: "Karotten", amount: 300, unit: "g", allergens: [] },
      { name: "Ingwer", amount: 15, unit: "g", allergens: [] },
      { name: "Haferflocken", amount: 80, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Sojasauce", amount: 1, unit: "EL", allergens: ["F"] },
      { name: "Öl", amount: 4, unit: "EL", allergens: [] },
    ],
    steps: [
      "Karotten fein raspeln, Ingwer reiben",
      "Mit Haferflocken, Ei und Sojasauce vermengen",
      "15 Minuten quellen lassen",
      "Bratlinge formen und in Öl goldbraun braten",
    ],
    allergens: ["A", "C", "F"],
  },
  "Kürbislaibchen": {
    ingredients: [
      { name: "Hokkaido-Kürbis", amount: 400, unit: "g", allergens: [] },
      { name: "Kartoffeln", amount: 200, unit: "g", allergens: [] },
      { name: "Eier", amount: 1, unit: "Stk", allergens: ["C"] },
      { name: "Semmelbrösel", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Kürbiskerne", amount: 30, unit: "g", allergens: [] },
      { name: "Öl", amount: 4, unit: "EL", allergens: [] },
    ],
    steps: [
      "Kürbis und Kartoffeln weich kochen und stampfen",
      "Mit Ei und Semmelbröseln vermengen",
      "Laibchen formen, in gehackten Kürbiskernen wenden",
      "In Öl goldbraun braten",
    ],
    allergens: ["A", "C"],
  },
  "Kartoffelpuffer": {
    ingredients: [
      { name: "Kartoffeln festkochend", amount: 600, unit: "g", allergens: [] },
      { name: "Eier", amount: 2, unit: "Stk", allergens: ["C"] },
      { name: "Mehl", amount: 30, unit: "g", allergens: ["A"] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Öl", amount: 100, unit: "ml", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Kartoffeln und Zwiebel fein reiben, gut ausdrücken",
      "Mit Eiern, Mehl und Salz vermengen",
      "Portionsweise in heißem Öl flach drücken und goldbraun braten",
      "Auf Küchenpapier abtropfen",
      "Mit Apfelmus oder Sauerrahm servieren",
    ],
    allergens: ["A", "C"],
  },

  // ══════════════════════════════════════════════════
  // CURRYS, EINTÖPFE & PFANNEN (10)
  // ══════════════════════════════════════════════════
  "Gemüsecurry mit Kokosmilch": {
    ingredients: [
      { name: "Karotten", amount: 150, unit: "g", allergens: [] },
      { name: "Zucchini", amount: 150, unit: "g", allergens: [] },
      { name: "Paprika", amount: 1, unit: "Stk", allergens: [] },
      { name: "Kokosmilch", amount: 400, unit: "ml", allergens: [] },
      { name: "Currypaste", amount: 2, unit: "EL", allergens: [] },
      { name: "Basmatireis", amount: 250, unit: "g", allergens: [] },
      { name: "Koriander frisch", amount: 1, unit: "Bund", allergens: [] },
      { name: "Öl", amount: 2, unit: "EL", allergens: [] },
    ],
    steps: [
      "Gemüse in mundgerechte Stücke schneiden",
      "Currypaste in Öl anbraten",
      "Gemüse zugeben und kurz anbraten",
      "Kokosmilch aufgießen, 15 Minuten köcheln",
      "Mit Koriander und Basmatireis servieren",
    ],
    allergens: [],
  },
  "Kichererbsen-Curry": {
    ingredients: [
      { name: "Kichererbsen (Dose)", amount: 400, unit: "g", allergens: [] },
      { name: "Tomaten (Dose)", amount: 400, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Ingwer", amount: 10, unit: "g", allergens: [] },
      { name: "Garam Masala", amount: 1, unit: "EL", allergens: [] },
      { name: "Kurkuma", amount: 1, unit: "TL", allergens: [] },
      { name: "Kokosmilch", amount: 200, unit: "ml", allergens: [] },
      { name: "Koriander", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Zwiebel, Knoblauch und Ingwer anbraten",
      "Gewürze einrühren, Tomaten zugeben",
      "Kichererbsen und Kokosmilch zugeben",
      "20 Minuten köcheln, mit Koriander servieren",
    ],
    allergens: [],
  },
  "Linsen-Dal": {
    ingredients: [
      { name: "Rote Linsen", amount: 250, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Ingwer", amount: 15, unit: "g", allergens: [] },
      { name: "Kurkuma", amount: 1, unit: "TL", allergens: [] },
      { name: "Kreuzkümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Kokosmilch", amount: 200, unit: "ml", allergens: [] },
      { name: "Tomaten (Dose)", amount: 200, unit: "g", allergens: [] },
      { name: "Koriander", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Linsen waschen",
      "Zwiebel, Knoblauch und Ingwer anbraten, Gewürze einrühren",
      "Linsen und Tomaten zugeben, mit Wasser bedecken",
      "20 Minuten kochen bis Linsen zerfallen",
      "Kokosmilch einrühren, mit Koriander servieren",
    ],
    allergens: [],
  },
  "Ratatouille": {
    ingredients: [
      { name: "Aubergine", amount: 1, unit: "Stk", allergens: [] },
      { name: "Zucchini", amount: 2, unit: "Stk", allergens: [] },
      { name: "Paprika", amount: 2, unit: "Stk", allergens: [] },
      { name: "Tomaten", amount: 400, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 3, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 4, unit: "EL", allergens: [] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Basilikum", amount: 4, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Gemüse waschen und in gleichmäßige Würfel schneiden",
      "Jede Sorte separat in Olivenöl anbraten",
      "Zwiebel und Knoblauch anschwitzen, Tomaten zugeben",
      "Alles zusammen mit Kräutern 20 Minuten schmoren",
      "Lauwarm oder kalt servieren",
    ],
    allergens: [],
  },
  "Chili sin Carne": {
    ingredients: [
      { name: "Kidneybohnen (Dose)", amount: 400, unit: "g", allergens: [] },
      { name: "Mais (Dose)", amount: 200, unit: "g", allergens: [] },
      { name: "Tomaten (Dose)", amount: 400, unit: "g", allergens: [] },
      { name: "Paprika", amount: 2, unit: "Stk", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Chili", amount: 1, unit: "Stk", allergens: [] },
      { name: "Kreuzkümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Sauerrahm", amount: 100, unit: "ml", allergens: ["G"] },
    ],
    steps: [
      "Zwiebel und Knoblauch anbraten, Paprika zugeben",
      "Tomaten, Bohnen, Mais und Gewürze zugeben",
      "30 Minuten köcheln lassen",
      "Mit Sauerrahm und Reis servieren",
    ],
    allergens: ["G"],
  },
  "Pilzragout": {
    ingredients: [
      { name: "Gemischte Pilze", amount: 500, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Schlagobers", amount: 200, unit: "ml", allergens: ["G"] },
      { name: "Weißwein", amount: 100, unit: "ml", allergens: ["O"] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Thymian", amount: 2, unit: "Stk", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
    ],
    steps: [
      "Pilze putzen und in Stücke schneiden",
      "In Butter bei starker Hitze anbraten",
      "Zwiebel und Knoblauch zugeben",
      "Mit Weißwein ablöschen, Schlagobers zugeben",
      "10 Minuten einkochen, mit Kräutern servieren",
    ],
    allergens: ["G", "O"],
  },
  "Eierschwammerl mit Knödel": {
    ingredients: [
      { name: "Eierschwammerl (Pfifferlinge)", amount: 500, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Butter", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Schlagobers", amount: 100, unit: "ml", allergens: ["G"] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Semmelknödel", amount: 4, unit: "Stk", allergens: ["A", "C", "G"] },
    ],
    steps: [
      "Eierschwammerl putzen (nicht waschen!), größere halbieren",
      "Zwiebel in Butter anschwitzen",
      "Eierschwammerl zugeben und 5 Minuten braten",
      "Schlagobers zugeben, kurz einkochen",
      "Mit Petersilie und Semmelknödeln servieren",
    ],
    allergens: ["A", "C", "G"],
  },
  "Erdäpfelgulasch": {
    ingredients: [
      { name: "Kartoffeln", amount: 800, unit: "g", allergens: [] },
      { name: "Zwiebeln", amount: 200, unit: "g", allergens: [] },
      { name: "Paprikapulver edelsüß", amount: 2, unit: "EL", allergens: [] },
      { name: "Tomatenmark", amount: 1, unit: "EL", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Kümmel", amount: 1, unit: "TL", allergens: [] },
      { name: "Debreziner", amount: 2, unit: "Stk", allergens: [] },
      { name: "Essig", amount: 1, unit: "EL", allergens: [] },
      { name: "Gemüsebrühe", amount: 600, unit: "ml", allergens: ["L"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zwiebeln in Öl goldbraun rösten",
      "Paprikapulver einrühren, mit Essig ablöschen",
      "Tomatenmark einrühren, Kartoffelstücke und Brühe zugeben",
      "Kümmel und Knoblauch zugeben, 20 Minuten kochen",
      "Debreziner in Scheiben zugeben, 5 Minuten mitkochen",
      "Soll dicklich sein — Kartoffeln binden die Sauce",
    ],
    allergens: ["L"],
  },
  "Gemüsepfanne": {
    ingredients: [
      { name: "Zucchini", amount: 150, unit: "g", allergens: [] },
      { name: "Paprika bunt", amount: 2, unit: "Stk", allergens: [] },
      { name: "Champignons", amount: 150, unit: "g", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Olivenöl", amount: 3, unit: "EL", allergens: [] },
      { name: "Sojasauce", amount: 2, unit: "EL", allergens: ["F"] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Gemüse waschen und in Streifen bzw. Scheiben schneiden",
      "Im Wok oder großer Pfanne portionsweise in Öl scharf anbraten",
      "Sojasauce einrühren und schwenken",
      "Gemüse soll noch Biss haben",
      "Mit Reis oder Nudeln servieren",
    ],
    allergens: ["F"],
  },
  "Wok-Gemüse mit Sojasauce": {
    ingredients: [
      { name: "Brokkoli", amount: 150, unit: "g", allergens: [] },
      { name: "Paprika", amount: 1, unit: "Stk", allergens: [] },
      { name: "Karotten", amount: 100, unit: "g", allergens: [] },
      { name: "Champignons", amount: 100, unit: "g", allergens: [] },
      { name: "Zuckerschoten", amount: 100, unit: "g", allergens: [] },
      { name: "Sojasauce", amount: 3, unit: "EL", allergens: ["F"] },
      { name: "Sesamöl", amount: 1, unit: "EL", allergens: ["N"] },
      { name: "Ingwer", amount: 10, unit: "g", allergens: [] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Gemüse in mundgerechte Stücke schneiden",
      "Ingwer und Knoblauch fein hacken",
      "Wok stark erhitzen, Sesamöl zugeben",
      "Gemüse portionsweise scharf anbraten",
      "Sojasauce einrühren, kurz schwenken",
      "Mit Reis servieren",
    ],
    allergens: ["F", "N"],
  },

  // ══════════════════════════════════════════════════
  // GEFÜLLT & ÜBERBACKEN (5)
  // ══════════════════════════════════════════════════
  "Gefüllte Paprika": {
    ingredients: [
      { name: "Paprika (groß)", amount: 4, unit: "Stk", allergens: [] },
      { name: "Reis", amount: 150, unit: "g", allergens: [] },
      { name: "Faschiertes", amount: 300, unit: "g", allergens: [] },
      { name: "Zwiebel", amount: 1, unit: "Stk", allergens: [] },
      { name: "Knoblauch", amount: 1, unit: "Stk", allergens: [] },
      { name: "Tomatenpassata", amount: 500, unit: "ml", allergens: [] },
      { name: "Paprikapulver", amount: 1, unit: "TL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Reis halbgar kochen",
      "Faschiertes mit Zwiebel, Knoblauch und Reis mischen",
      "Paprika entkernen und füllen",
      "In Auflaufform stellen, Tomatenpassata darüber gießen",
      "Bei 180°C 45 Minuten garen",
    ],
    allergens: [],
  },
  "Gefüllte Zucchini": {
    ingredients: [
      { name: "Zucchini (groß)", amount: 4, unit: "Stk", allergens: [] },
      { name: "Couscous", amount: 100, unit: "g", allergens: ["A"] },
      { name: "Schafkäse", amount: 100, unit: "g", allergens: ["G"] },
      { name: "Tomaten", amount: 2, unit: "Stk", allergens: [] },
      { name: "Olivenöl", amount: 2, unit: "EL", allergens: [] },
      { name: "Minze", amount: 1, unit: "EL", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Zucchini halbieren und aushöhlen",
      "Couscous mit kochendem Wasser übergießen und quellen lassen",
      "Couscous, Schafkäse, Tomaten und Minze mischen",
      "Zucchinihälften füllen",
      "Bei 180°C 25 Minuten backen",
    ],
    allergens: ["A", "G"],
  },
  "Überbackene Auberginen": {
    ingredients: [
      { name: "Auberginen", amount: 3, unit: "Stk", allergens: [] },
      { name: "Tomatensauce", amount: 300, unit: "ml", allergens: [] },
      { name: "Mozzarella", amount: 200, unit: "g", allergens: ["G"] },
      { name: "Parmesan", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Olivenöl", amount: 4, unit: "EL", allergens: [] },
      { name: "Basilikum", amount: 4, unit: "Stk", allergens: [] },
    ],
    steps: [
      "Auberginen in Scheiben schneiden, salzen, 15 Min entwässern",
      "In Olivenöl goldbraun braten",
      "Schichten: Auberginen, Tomatensauce, Mozzarella",
      "Parmesan darüber streuen",
      "Bei 180°C 25 Minuten überbacken",
    ],
    allergens: ["G"],
  },
  "Stuffed Mushrooms / Gefüllte Champignons": {
    ingredients: [
      { name: "Riesenchampignons", amount: 8, unit: "Stk", allergens: [] },
      { name: "Semmelbrösel", amount: 50, unit: "g", allergens: ["A"] },
      { name: "Parmesan", amount: 40, unit: "g", allergens: ["G"] },
      { name: "Knoblauch", amount: 2, unit: "Stk", allergens: [] },
      { name: "Petersilie", amount: 1, unit: "Bund", allergens: [] },
      { name: "Olivenöl", amount: 3, unit: "EL", allergens: [] },
    ],
    steps: [
      "Champignons putzen, Stiele herausdrehen und hacken",
      "Gehackte Stiele mit Semmelbröseln, Parmesan und Knoblauch mischen",
      "Champignonköpfe füllen",
      "Mit Olivenöl beträufeln",
      "Bei 200°C 15 Minuten backen",
    ],
    allergens: ["A", "G"],
  },
  "Melanzani-Parmigiana": {
    ingredients: [
      { name: "Auberginen", amount: 3, unit: "Stk", allergens: [] },
      { name: "Tomatensauce", amount: 500, unit: "ml", allergens: [] },
      { name: "Mozzarella", amount: 250, unit: "g", allergens: ["G"] },
      { name: "Parmesan", amount: 60, unit: "g", allergens: ["G"] },
      { name: "Basilikum", amount: 1, unit: "Bund", allergens: [] },
      { name: "Olivenöl", amount: 100, unit: "ml", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Auberginen in Scheiben schneiden, salzen und entwässern",
      "In Olivenöl goldbraun braten (oder im Ofen backen)",
      "Schichtweise mit Tomatensauce, Mozzarella und Basilikum aufbauen",
      "Parmesan obenauf",
      "Bei 180°C 30 Minuten backen",
    ],
    allergens: ["G"],
  },

  // ══════════════════════════════════════════════════
  // SONSTIGES (4)
  // ══════════════════════════════════════════════════
  "Eierspeise / Bauernomelett": {
    ingredients: [
      { name: "Eier", amount: 8, unit: "Stk", allergens: ["C"] },
      { name: "Milch", amount: 50, unit: "ml", allergens: ["G"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Eier mit Milch und Salz verquirlen",
      "In heißer Butter stocken lassen",
      "Dabei langsam mit Gabel vom Rand zur Mitte schieben",
      "Soll innen noch cremig sein!",
      "Mit Schnittlauch bestreuen, mit Brot servieren",
    ],
    allergens: ["C", "G"],
  },
  "Kaiserschmarrn": {
    ingredients: [
      { name: "Mehl", amount: 200, unit: "g", allergens: ["A"] },
      { name: "Milch", amount: 250, unit: "ml", allergens: ["G"] },
      { name: "Eier", amount: 4, unit: "Stk", allergens: ["C"] },
      { name: "Zucker", amount: 30, unit: "g", allergens: [] },
      { name: "Rosinen", amount: 40, unit: "g", allergens: ["O"] },
      { name: "Butter", amount: 50, unit: "g", allergens: ["G"] },
      { name: "Staubzucker", amount: 2, unit: "EL", allergens: [] },
      { name: "Vanillezucker", amount: 1, unit: "TL", allergens: [] },
    ],
    steps: [
      "Eier trennen: Eiweiß steif schlagen",
      "Eigelb mit Zucker schaumig rühren, Milch und Mehl einrühren",
      "Eischnee vorsichtig unterheben",
      "In heißer Butter goldbraun backen, mit Gabeln zerreißen",
      "Rosinen und Zucker zugeben, karamellisieren",
      "Mit Staubzucker und Zwetschgenröster servieren",
    ],
    allergens: ["A", "C", "G", "O"],
  },
  "Palatschinken gefüllt": {
    ingredients: [
      { name: "Mehl", amount: 200, unit: "g", allergens: ["A"] },
      { name: "Eier", amount: 3, unit: "Stk", allergens: ["C"] },
      { name: "Milch", amount: 300, unit: "ml", allergens: ["G"] },
      { name: "Topfen", amount: 250, unit: "g", allergens: ["G"] },
      { name: "Zucker", amount: 40, unit: "g", allergens: [] },
      { name: "Vanillezucker", amount: 1, unit: "TL", allergens: [] },
      { name: "Rosinen", amount: 30, unit: "g", allergens: ["O"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
    ],
    steps: [
      "Aus Mehl, Eiern und Milch glatten Teig rühren, 30 Min rasten",
      "Dünne Palatschinken backen",
      "Topfenfüllung: Topfen mit Zucker, Vanille und Rosinen mischen",
      "Palatschinken füllen, einrollen und in Auflaufform legen",
      "Bei 180°C 15 Minuten überbacken",
      "Mit Staubzucker und Fruchtröster servieren",
    ],
    allergens: ["A", "C", "G", "O"],
  },
  "Knödel mit Ei": {
    ingredients: [
      { name: "Semmelknödel (vom Vortag)", amount: 4, unit: "Stk", allergens: ["A", "C", "G"] },
      { name: "Eier", amount: 4, unit: "Stk", allergens: ["C"] },
      { name: "Butter", amount: 30, unit: "g", allergens: ["G"] },
      { name: "Schnittlauch", amount: 1, unit: "Bund", allergens: [] },
      { name: "Salz", amount: 1, unit: "Prise", allergens: [] },
    ],
    steps: [
      "Knödel in Scheiben schneiden",
      "In Butter goldbraun anbraten",
      "Eier verquirlen und darüber gießen",
      "Stocken lassen, mit Schnittlauch servieren",
      "Dazu grüner Salat",
    ],
    allergens: ["A", "C", "G"],
  },
};
